#!/usr/bin/env python3
"""announced_work_guard — Stop gate on ending a turn with work announced, not done.

The failure it mechanizes, measured rather than imagined. In one long session
(2026-08-12, 314 turns) seven turns ended on a present-tense claim of work in
progress — "Starting the IR-38 audit.", "Proceeding with step 3." — with zero
tool calls after the sentence. Nothing had started. Asked how often, the model
audited itself and reported TWO. The real number was seven.

That gap is the point. This is not a diligence problem, it is a self-report
problem: an announcement is generated by the same fluent process as everything
else, so it reads identical whether or not the thing happened, and the model
cannot tell from the inside. The user's words: "I can't always babysit that."

The house rule this makes mechanical is AGENTS.md's: verification authority
lives outside the model, and a claim needs evidence checked at the same scope.
A claim about MY OWN execution is not exempt, and it is the one claim I had
never gated.

WHY A STOP HOOK IS THE RIGHT SEAM. At Stop the turn is already ending, so by
construction nothing can run after the final text. The check therefore needs no
transcript walk and no turn segmentation: if the last thing said announces
imminent action, that action is not going to happen.

WHAT THIS CANNOT DO. It reads the tail of one message. It cannot tell a
sincere announcement from a rhetorical one, it cannot catch work promised in
the middle of a message and quietly dropped, and it says nothing about whether
the work that DID run was any good. Blocking here costs one turn; missing costs
the user's trust in every status line, which is why it is tuned to fire.

Contract, verified in-binary (Claude Code 2.1.227): Stop hooks receive
{"hook_event_name": "Stop", "stop_hook_active": bool,
 "last_assistant_message": ..., "session_id", "transcript_path", ...}.
Exit 2 blocks the stop and returns stderr to the model. `stop_hook_active` is
the documented loop guard — the binary warns "check stop_hook_active in the
input and return success while it's true" and caps consecutive blocks
(CLAUDE_CODE_STOP_HOOK_BLOCK_CAP).

    python3 ~/.claude/hooks/announced_work_guard.py            # as a hook
    python3 ~/.claude/hooks/announced_work_guard.py --selftest # controls

Exit codes: 0 allow (no announcement, or out of scope) · 2 block, with the
reason on stderr · 1 selftest failure.
"""
import json
import os
import re
import sys

VERSION = "1.0.0"

# An announcement of imminent action BY ME, anchored to the TAIL of the final
# message. The same words mid-message are ordinary narration of work that then
# happens; only at the boundary do they become a claim with nothing behind it.
ANNOUNCE = re.compile(
    # NOT `-\s*` in the prefix: it matched the hyphen inside `long-running`
    # and fired on five turns across three projects that never announced
    # anything. Em-dash is a real clause lead; hyphen is part of a word.
    r'(?:^|[.!?\n]\s*|—\s*)'
    r'(?:'
    # The participle must lead into an OBJECT — "Starting the audit",
    # "Continuing with the merge class". `Continuing to wait/collect/hold` is a
    # description of an ongoing state, usually while background agents run, and
    # ending the turn there is correct. That distinction is 4 of the 10 false
    # positives measured across 696 transcripts.
    r'(?:Starting|Running|Proceeding|Continuing|Beginning|Kicking off|Firing off)'
    r'\s+(?:with|on|the|a|an)\b'
    r'|(?:Let me|Let\'s)\s+(?:now\s+|go\s+ahead\s+and\s+)?'
    r'(?:start|run|check|look|do|go|build|fix|verify|audit|dig|pull|open|read|grep|sweep|write|take)'
    # `I'll <verb>` REQUIRES an imminence marker. Bare "I'll verify X" is far
    # more often a standing policy or a sequencing note than a claim to be
    # acting now — measured on real transcripts, that arm produced 3 of 4 false
    # positives ("I'll verify each agent's sharpest claim myself, as before").
    # The present participles carry the failure on their own.
    r'|I\'?ll\s+(?:now|go\s+ahead\s+and)\s+'
    r'(?:start|run|check|look|do|build|fix|verify|audit|dig|pull|open|read|write|kick|take)'
    r'|(?:On it|Doing that now|Running that now|Starting now|Working on it)\b'
    r')',
    re.I)

# Legitimate ways to end a turn. These must never be blocked: handing the
# decision back is the correct move, and gating it would push the model toward
# acting without approval - the opposite failure, and a worse one.
HANDBACK = re.compile(
    r'(stopping here|stopped here|say go|your call|let me know|over to you|'
    r'waiting on|want me to|shall I|should I|do you want|which (would|do) you|'
    r'before I (start|proceed|continue|touch|change)|say the word|'
    r'happy to .{0,30}if you|unless you|if you\'d rather|continuing to (wait|collect|hold|monitor|poll|watch))', re.I)

# The boundary is the LAST SENTENCE OR TWO, not a character window. A window
# was the first design and its own control caught it: on a short message the
# window is the whole message, so "Let me check the register. …I checked it:
# 47 markers. Committed d5e1a26." blocked - an announcement that was narration
# of work the same message then reported doing. Position in the message is the
# whole discriminator, so it has to be measured in sentences.
TAIL_UNITS = 2

# A "unit" ends at a sentence terminator OR at a structural break, because prose
# punctuation is not the only thing that ends a thought. Splitting on `[.!?]`
# alone was the second bug this file's own controls caught: a message ending in
# a table, a bullet list or a code fence has no terminal punctuation near the
# end, so an announcement three paragraphs up landed inside "the last sentence"
# and blocked. Messages here end in tables constantly, so that would have fired
# all day and taught the reader to ignore the gate.
SPLIT = re.compile(
    r'(?<=[.!?])[\s\n]+'                       # end of a sentence
    r'|\n\s*\n'                                # paragraph break
    r'|\n(?=\s*(?:[|\-*+>#]|\d+[.)]|```))'     # table row, list item, quote,
)                                              # heading, fence


def boundary(text):
    parts = [p for p in SPLIT.split(text.strip()) if p and p.strip()]
    return " ".join(parts[-TAIL_UNITS:]) if parts else ""

BLOCK_MSG = """\
STOP BLOCKED — announced-work guard ({v}).

Your final sentence announces work you have not started: {trigger!r}

At Stop the turn is over, so nothing can run after it. As written this is a
status claim with no execution behind it, and the reader cannot tell the
difference from the outside. Measured base rate for this failure in one
session: 7 turns of 314, self-reported as 2.

Do exactly one of these, now:
  1. Make the tool calls. If you meant it, the calls belong in THIS turn.
  2. Rewrite the ending without the announcement — report what you DID (past
     tense, from tool output), then state the next step as a proposal:
     "next step is X, say go" or "stopping here".

Do not restate the intention in different words. That is the same claim."""

DRIFT_MSG = """\
STOP BLOCKED — announced-work guard ({v}) HAS GONE BLIND.

{why}

This guard reads `last_assistant_message` from the Stop envelope. It cannot
read this one, so it is not checking anything — and a checker that passes
because it read nothing is worse than no checker, because it still reads as
green. Blocking once so this is seen rather than silently inherited.

This is a HARNESS defect, not a defect in the turn. Fix
~/.claude/hooks/announced_work_guard.py against the current Stop contract, or
set ANNOUNCED_WORK_GUARD=off to disable it deliberately. The retry carries
stop_hook_active, so the turn will end normally and this will not loop."""


class EnvelopeDrift(ValueError):
    """The Stop envelope no longer carries a message this guard can read.

    Returning "allow" here is the failure this whole file exists to prevent: a
    renamed or dropped field would make the gate silently pass every turn,
    forever, while reading as a healthy hook. The house pattern in
    askq_timeout_guard separates UNRECOGNISED (schema changed) from
    OUT_OF_SCOPE (legitimately not ours), and only the first is loud.

    Drift blocks ONCE. `stop_hook_active` is true on the retry, so the guard
    returns success and the turn ends — the operator sees it, and a genuinely
    dead field costs one turn rather than wedging the session.
    """


def message_text(payload):
    """The last assistant message as plain text, however it is shaped."""
    if not isinstance(payload, dict):
        raise EnvelopeDrift(f"stdin parsed to {type(payload).__name__}, expected a JSON object")
    if "last_assistant_message" not in payload:
        raise EnvelopeDrift("envelope has no 'last_assistant_message' key — "
                            "the Stop payload schema changed")
    m = payload.get("last_assistant_message")
    if isinstance(m, str):
        return m
    if isinstance(m, dict):
        c = m.get("content")
        if isinstance(c, str):
            return c
        if isinstance(c, list):
            return "\n".join(b.get("text", "") for b in c
                             if isinstance(b, dict) and b.get("type") == "text")
    if isinstance(m, list):
        return "\n".join(b.get("text", "") for b in m
                         if isinstance(b, dict) and b.get("type") == "text")
    if m is None:
        return ""            # present and empty is a real, readable state
    raise EnvelopeDrift(f"last_assistant_message is a {type(m).__name__}, "
                        f"not str/dict/list — shape changed")


def judge(payload):
    """-> trigger string to block on, or None to allow."""
    if isinstance(payload, dict) and payload.get("stop_hook_active"):
        return None                     # documented loop guard; never re-block
    text = message_text(payload).strip()
    if not text:
        return None                     # nothing read is not evidence of a defect
    tail = boundary(text)
    # A turn that ends on a QUESTION is asking, not claiming — whatever was
    # said before it. Found on a real transcript: a message opening "Starting
    # with a mechanical producer-existence check" and closing "Does the
    # fifth-entity model look right to you before I write any of it?" blocked,
    # which would have punished the exact behaviour the rule wants.
    if text.rstrip().endswith("?"):
        return None
    if HANDBACK.search(tail):
        return None
    m = ANNOUNCE.search(tail)
    return m.group(0).strip() if m else None


def selftest():
    cases = [
        ("real violation, session 2026-08-12",
         {"last_assistant_message": "…needs the finding corrected, not the corpus.\n\n"
                                    "Starting the IR-38 audit."}, True),
        ("real violation, the other one",
         {"last_assistant_message": "Still worth doing while the mapping is in hand, "
                                    "but it's tidying, not repair.\n\nProceeding with step 3."}, True),
        ("handback is not a violation",
         {"last_assistant_message": "That one needs a decision. Next step is the "
                                    "propagation batch — say go and I'll start."}, False),
        ("plain report is not a violation",
         {"last_assistant_message": "Committed 19c57aa. 14 gates green, 56 of 88 fixed."}, False),
        ("announcement mid-message, work then done, is not a violation",
         {"last_assistant_message": "Let me check the register. …I checked it: 47 markers, "
                                    "all bound. Committed d5e1a26."}, False),
        ("loop guard: never block twice",
         {"last_assistant_message": "Starting the audit.", "stop_hook_active": True}, False),
        ("empty message is not a verdict",
         {"last_assistant_message": ""}, False),
        ("content-block shape parses",
         {"last_assistant_message": {"content": [{"type": "text", "text": "On it."}]}}, True),

        # Structural endings. Every one of these blocked under the first two
        # designs; messages here end in a table more often than in a sentence,
        # so a gate that fires on them is a gate the reader learns to ignore.
        ("ends in a table",
         {"last_assistant_message": "Let me check the register first.\n\n"
                                    "| gate | state |\n|---|---|\n| residue | green |"}, False),
        ("ends in a bullet list",
         {"last_assistant_message": "I'll run the audit and report.\n\n"
                                    "- F20 live\n- F90 live"}, False),
        ("ends in a code fence",
         {"last_assistant_message": "Let me look at the hook.\n\n"
                                    "```python\nx = 1\n```"}, False),
        ("ends in a numbered list",
         {"last_assistant_message": "Let me start on the batch.\n\n"
                                    "1. F20\n2. F90"}, False),
        ("ends in a heading",
         {"last_assistant_message": "Let me dig in.\n\n## What I found\n\n### Detail"}, False),

        # No punctuation anywhere must still be judged, or the shortest and
        # bluntest form of the failure is the one that walks through.
        ("bare announcement, no punctuation at all",
         {"last_assistant_message": "Starting the audit"}, True),
        ("announcement trailing into one long unpunctuated clause",
         {"last_assistant_message": "Starting the IR-38 audit and I expect it will take "
                                    "a while because there are seven claims"}, True),
        ("a question is a handback, not an announcement",
         {"last_assistant_message": "Should I start the audit?"}, False),
        ("handback wins even when an announcement appears earlier",
         {"last_assistant_message": "Starting sounds right. Let me know which you prefer."},
         False),

        # Verbatim from other projects' transcripts. Every one of these blocked
        # under the sentence-split design; three of the four were behaviour the
        # rule wants MORE of, which is how a gate teaches people to disable it.
        ("real FP: opens with an announcement, ends asking for approval",
         {"last_assistant_message": "Starting with a mechanical producer-existence check I can "
                                    "run against the schema block.\n\nDoes the fifth-entity model "
                                    "look right to you before I write any of it?"}, False),
        ("real FP: a standing policy about method, not imminent action",
         {"last_assistant_message": "I'll verify each agent's sharpest claim myself before it "
                                    "reaches you, as before."}, False),
        ("real FP: sequencing note, not a claim to be acting",
         {"last_assistant_message": "I'll audit R7-B against the register before starting it, "
                                    "per the order."}, False),
        ("real TP: same shape as the ones this was built for",
         {"last_assistant_message": "The preimage lint now tracks both and holds them "
                                    "consistent.\n\nContinuing with the merge class — currently "
                                    "the only entity that fits no merge class."}, True),
        ("`I'll` still fires when imminence is explicit",
         {"last_assistant_message": "That settles it. I'll now run the audit."}, True),
    ]
    failures = 0
    cases += [
        # Envelope drift. Silently allowing here would make the gate pass every
        # turn forever while reading as a healthy hook - the exact
        # unvalidated-instrument failure the rest of this harness exists to
        # stop. Each of these must be LOUD, and each blocks only once.
        ("drift: the field is renamed",
         {"hook_event_name": "Stop", "assistant_message": "Starting the audit."}, "drift"),
        ("drift: the field is gone entirely",
         {"hook_event_name": "Stop", "session_id": "x"}, "drift"),
        ("drift: the message is an alien shape",
         {"last_assistant_message": 42}, "drift"),
        ("drift: stdin is not an object",
         ["Starting the audit."], "drift"),
        ("drift blocks ONCE, not forever",
         {"stop_hook_active": True, "session_id": "x"}, False),
        ("present-but-null is a readable state, not drift",
         {"last_assistant_message": None}, False),
    ]
    for name, payload, want in cases:
        try:
            got = judge(payload) is not None
        except EnvelopeDrift:
            got = "drift"
        if got != want:
            failures += 1
        label = got if isinstance(got, str) else ("block" if got else "allow")
        print(f"  {'PASS' if got == want else 'FAIL'} {name} -> {label}")
    print(f"\n  selftest: {failures} failure(s)")
    print(f"SELFTEST-SUMMARY suite=announced_work_guard checks={len(cases)} "
          f"failures={failures}")
    return failures == 0


def main(argv):
    if "--selftest" in argv:
        return 0 if selftest() else 1
    off = os.environ.get("ANNOUNCED_WORK_GUARD") == "off"
    raw = sys.stdin.read()
    try:
        payload = json.loads(raw)
    except Exception as exc:
        if off:
            return 0
        print(DRIFT_MSG.format(v=VERSION, why=f"stdin is not JSON ({exc})"), file=sys.stderr)
        return 2
    if isinstance(payload, dict) and \
            payload.get("hook_event_name") not in (None, "Stop", "SubagentStop"):
        return 0                        # out of scope, which is not drift
    try:
        trigger = judge(payload)
    except EnvelopeDrift as exc:
        if off:
            return 0
        print(DRIFT_MSG.format(v=VERSION, why=str(exc)), file=sys.stderr)
        return 2
    if not trigger or off:
        return 0
    print(BLOCK_MSG.format(v=VERSION, trigger=trigger), file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
