#!/usr/bin/env python3
"""announced_work_guard — Stop gate on ending a turn with work announced, not done.

The failure it mechanizes, measured rather than imagined. In one long session
(2026-08-12, 314 turns) seven turns ended on a present-tense claim of work in
progress — "Starting the IR-38 audit.", "Proceeding with step 3." — with zero
tool calls after the sentence. Nothing had started. Asked how often, the model
audited itself and reported TWO. The real number was seven.

That gap is the point. This is not a diligence problem, it is a self-report
problem: an announcement is generated by the same fluent process as everything
else, so it reads identical whether or not the thing happened, and the model
cannot tell from the inside. The user's words: "I can't always babysit that."

The house rule this makes mechanical is AGENTS.md's: verification authority
lives outside the model, and a claim needs evidence checked at the same scope.
A claim about MY OWN execution is not exempt, and it is the one claim I had
never gated.

WHY A STOP HOOK IS THE RIGHT SEAM. At Stop the turn is already ending, so by
construction nothing can run after the final text. The check therefore needs no
transcript walk and no turn segmentation: if the last thing said announces
imminent action, that action is not going to happen.

THE SAME DEFECT POINTS BOTH WAYS. Announcing work with nothing behind it is one
half. The other is ending a turn with an all-clear while background work is
still armed - the reader's own screen then contradicts the claim, which costs
more trust than the first case. The Stop envelope already carries
`background_tasks` and `session_crons` for exactly this: the runtime's words are
that they let a hook "distinguish 'session is done' from 'session is paused
waiting for background work to wake it'". So the guard reads them, and blocks a
denial the envelope refutes. It reports each `id`, because no query surface the
model has will list these - TaskList is the to-do board, ListAgents lists
addressable agents, and an in-process websocket watch never appears in `ps`.

WHAT THIS CANNOT DO. It reads the tail of one message plus two envelope fields.
It cannot tell a sincere announcement from a rhetorical one, it cannot catch work
promised in the middle of a message and quietly dropped, it cannot see state the
runtime does not report in the envelope, and it says nothing about whether the
work that DID run was any good. Blocking here costs one turn; missing costs the
user's trust in every status line, which is why it is tuned to fire.

CONTRACT, VERIFIED THREE WAYS rather than read once. (1) In-binary against
Claude Code 2.1.227. (2) Against a REAL captured Stop envelope, shipped as
hooks/fixtures_stop/S1_stop_real_envelope.json and asserted field-by-field in the
selftest — `last_assistant_message` is a plain str, `stop_hook_active` a bool.
(3) End to end in a live headless session: a run told to answer "Starting the
audit." was blocked at Stop, received this guard's message, and rewrote its
ending to "no work was performed, no tools were run, and nothing is pending".
The measurement behind the tuning is re-runnable, not a literal:
`announced_work_guard.py --sweep` regenerates it over any transcript glob.

Stop hooks receive
{"hook_event_name": "Stop", "stop_hook_active": bool,
 "last_assistant_message": ..., "session_id", "transcript_path", ...}.
Exit 2 blocks the stop and returns stderr to the model. `stop_hook_active` is
the documented loop guard — the binary warns "check stop_hook_active in the
input and return success while it's true" and caps consecutive blocks
(CLAUDE_CODE_STOP_HOOK_BLOCK_CAP).

    python3 ~/.claude/hooks/announced_work_guard.py            # as a hook
    python3 ~/.claude/hooks/announced_work_guard.py --selftest # controls

Exit codes: 0 allow (no announcement, or out of scope) · 2 block, with the
reason on stderr · 1 selftest failure.
"""
import json
import os
import hashlib
import re
import subprocess
import sys
import time
import traceback

VERSION = "1.0.0"

# An announcement of imminent action BY ME, anchored to the TAIL of the final
# message. The same words mid-message are ordinary narration of work that then
# happens; only at the boundary do they become a claim with nothing behind it.
ANNOUNCE = re.compile(
    # NOT `-\s*` in the prefix: it matched the hyphen inside `long-running`
    # and fired on five turns across three projects that never announced
    # anything. Em-dash is a real clause lead; hyphen is part of a word.
    r'(?:^|[.!?\n]\s*|—\s*)'
    r'(?:'
    # The participle must lead into an OBJECT — "Starting the audit",
    # "Continuing with the merge class". `Continuing to wait/collect/hold` is a
    # description of an ongoing state, usually while background agents run, and
    # ending the turn there is correct: that distinction was the largest single
    # class of false positive measured on the corpus of the day. It is now carried by
    # HANDBACK's `continuing to <verb>` arm rather than by this object slot, which
    # admits `to` — the two must move together or that class reopens.
    r'(?:Starting|Running|Proceeding|Continuing|Beginning|Kicking off|Firing off)'
    # The object slot. `with|on|the|a|an` alone allowed three measured turn-ends
    # through: `Kicking off that research now.`, `Starting Phase 1 -`, `Proceeding to
    # the doc pass now.` Two of the three carry `now`, the strongest signal there is.
    # NOTE the scoped (?-i:) - this pattern is compiled re.I, so a bare [A-Z] matches
    # lowercase and turns this gate into `any token`, which is the same matcher as no
    # gate at all (4.3x the block rate on the measured corpus).
    r'\s+(?:'
    r'(?:with|on|to|the|a|an|that|this|these|those|my|our|its|their)\b'
    r"|(?-i:[A-Z])[\w.'-]*"          # a named target: Phase 1, IR-38, F90
    r'|[`"\u201c]'                    # a quoted or backticked target
    r'|\d'                            # a numbered target
    r')'
    r'|(?:Let me|Let\'s)\s+(?:now\s+|go\s+ahead\s+and\s+)?'
    r'(?:start|run|check|look|do|go|build|fix|verify|audit|dig|pull|open|read|grep|sweep|write|take)'
    # `I'll <verb>` REQUIRES an imminence marker. Bare "I'll verify X" is far
    # more often a standing policy or a sequencing note than a claim to be
    # acting now. Re-measured with --sweep: dropping the imminence requirement
    # adds 7 blocks, of which 5 are standing-policy or conditional statements
    # ("I'll verify each agent's sharpest claim myself, as before").
    # The present participles carry the failure on their own.
    r'|I\'?ll\s+(?:now|go\s+ahead\s+and)\s+'
    r'(?:start|run|check|look|do|build|fix|verify|audit|dig|pull|open|read|write|kick|take)'
    r'|(?:On it|Doing that now|Running that now|Starting now|Working on it)\b'
    r')',
    re.I)

# Legitimate ways to end a turn. These must never be blocked: handing the
# decision back is the correct move, and gating it would push the model toward
# acting without approval - the opposite failure, and a worse one.
HANDBACK = re.compile(
    r'(stopping here|stopped here|say go|your call|let me know|over to you|'
    r'waiting on|want me to|shall I|should I|do you want|which (would|do) you|'
    r'before I (start|proceed|continue|touch|change)|say the word|'
    r'happy to .{0,30}if you|unless you|if you\'d rather|'
    r'continuing to (wait|collect|hold|monitor|poll|watch))', re.I)

# A DENIAL that anything is in flight. This is the mirror of ANNOUNCE: that arm
# catches a claim to be working with nothing behind it, and this one catches a
# claim that nothing is working while the envelope says otherwise. Both are the
# same defect - a work signal the reader cannot check from the outside.
#
# Deliberately NOT "all done" / "everything complete": those are claims about the
# TASK, not about session state, and they end turns constantly. Measured over 2281
# turn-endings, this arm matches 16.
QUIESCENT = re.compile(
    r"nothing\s+(?:is\s+|'s\s+|else\s+)?(?:currently\s+|still\s+|left\s+)?"
    r"(?:running|pending|in[\s-]flight|queued|armed|outstanding|active|to\s+wait\s+(?:for|on))"
    r"|no(?:thing)?\s+(?:background\s+|pending\s+|other\s+)?"
    r"(?:work|tasks?|agents?|jobs?|monitors?|watches|subscriptions?)\s+"
    r"(?:are\s+|is\s+)?(?:running|pending|in[\s-]flight|left|outstanding|armed|active)"
    r"|nothing\s+(?:is\s+)?(?:left|remaining|in\s+progress)"
    r"|no\s+(?:tools?\s+(?:were|are)\s+run|work\s+was\s+performed)"
    r"|nothing\s+running", re.I)

# A denial that names its own exception is an accurate report, not a false
# all-clear. "Nothing running except the two agents" is the honest form and must
# pass. This arm was NOT taste: it is the one suppression among the 16 measured
# matches, and it is a real turn ending from the corpus. `still` is deliberately
# absent - "Nothing outstanding. Still holding on your call" waits on the USER,
# not on background work, so it is a genuine all-clear and must stay blockable.
QUALIFIED = re.compile(r"\b(?:except|other than|besides|apart from|aside from|"
                       r"save for|but the|but for)\b", re.I)

# The boundary is the LAST SENTENCE OR TWO, not a character window. A window
# was the first design and its own control caught it: on a short message the
# window is the whole message, so "Let me check the register. …I checked it:
# 47 markers. Committed d5e1a26." blocked - an announcement that was narration
# of work the same message then reported doing. Position in the message is the
# whole discriminator, so it has to be measured in sentences.
TAIL_UNITS = 2

# Ceiling on the text handed to the matchers. 32 KB costs 36 ms end to end and
# 10 MB costs 1.9 s; the registered timeout is the wall that matters, not the cost.
MAX_JUDGED = 65536

# A "unit" ends at a sentence terminator OR at a structural break, because prose
# punctuation is not the only thing that ends a thought. Splitting on `[.!?]`
# alone was the second bug this file's own controls caught: a message ending in
# a table, a bullet list or a code fence has no terminal punctuation near the
# end, so an announcement three paragraphs up landed inside "the last sentence"
# and blocked. Messages here end in tables constantly, so that would have fired
# all day and taught the reader to ignore the gate.
SPLIT = re.compile(
    r'(?<=[.!?])[\s\n]+'                       # end of a sentence
    r'|\n\s*\n'                                # paragraph break
    r'|\n(?=\s*(?:[|\-*+>#]|\d+[.)]|```))'     # table row, list item, quote,
)                                              # heading, fence


def boundary(text):
    """The last TAIL_UNITS units, as units - the caller needs them apart.

    Joining them into one string with a space was the first shape and it threw away
    the very boundary SPLIT had just found: ANNOUNCE anchors on `^`, `[.!?\n]` or an
    em-dash, so an announcement whose preceding unit ends in a table pipe, a bullet,
    a heading or a colon lost its anchor and was allowed. Rejoining with `\n` keeps
    it, because `\n` is already in that anchor class.
    """
    # Bounded so a pathological message degrades to a fast decision rather than
    # a SIGTERM. The runtime does not truncate last_assistant_message, and a
    # hook killed at its timeout ends the turn with NO signal to the model and
    # none to the operator - measured: the only fully unobservable path there is.
    # Only the last TAIL_UNITS are read, so trimming the head is verdict-neutral.
    parts = [p for p in SPLIT.split(text.strip()[-MAX_JUDGED:]) if p and p.strip()]
    return parts[-TAIL_UNITS:]

BLOCK_MSG = """\
STOP BLOCKED — announced-work guard ({v}).

Your final sentence announces work you have not started: {trigger!r}

At Stop the turn is over, so nothing can run after it. As written this is a
status claim with no execution behind it, and the reader cannot tell the
difference from the outside. Measured base rate for this failure in one
session: 7 turns of 314, self-reported as 2. Regenerate with --sweep.

Do exactly one of these, now:
  1. Make the tool calls. If you meant it, the calls belong in THIS turn.
  2. Rewrite the ending without the announcement — report what you DID (past
     tense, from tool output), then state the next step as a proposal:
     "next step is X, say go" or "stopping here".

Do not restate the intention in different words. That is the same claim."""

STALE_MSG = """\
STOP BLOCKED — announced-work guard ({v}).

Your ending says {claim!r}, and the Stop envelope disagrees. Still in flight:

{rows}

This is the same defect as announcing work you have not started, pointed the
other way: a work signal the reader cannot check from the outside. It is worse
in one respect — the reader's own screen contradicts you, so the next thing they
lose is trust in every status line you write.

The ids above are the handle. `TaskStop` takes one directly, and no query
surface you have will list these for you: TaskList is the to-do board,
ListAgents lists addressable agents, and an in-process websocket watch never
appears in the process table. An empty result from any of those is not evidence
of absence.

Do exactly one of these, now:
  1. Stop the work, if it should not be running: TaskStop each id above.
  2. Rewrite the ending to say what is still armed and how it is cancelled.

Do not restate the all-clear in softer words. That is the same claim."""


DRIFT_MSG = """\
STOP BLOCKED — announced-work guard ({v}) HAS GONE BLIND.

{why}

This guard reads `last_assistant_message` from the Stop envelope. It cannot
read this one, so it is not checking anything — and a checker that passes
because it read nothing is worse than no checker, because it still reads as
green. Blocking once so this is seen rather than silently inherited.

This is a HARNESS defect, not a defect in the turn. Fix
~/.claude/hooks/announced_work_guard.py against the current Stop contract, or
set ANNOUNCED_WORK_GUARD=off to disable it deliberately. The retry carries
stop_hook_active, so the turn will end normally and this will not loop."""


def report_drift(why):
    """Block on stderr for the model AND on stdout for the operator.

    DRIFT_MSG is addressed to a person: it names a file to fix and an env var to
    set. Delivered on stderr alone it reaches only the model, which can do neither
    — and the operator's sole signal is a toast byte-identical to the one a
    successful block produces. askq_timeout_guard sets `systemMessage` on exactly
    this path for exactly this reason.

    Verified end to end: exit 2 with a stdout payload still blocks, and the
    systemMessage surfaces as an operator-facing record. Writing to stdout also
    closes a downgrade — the runtime demotes a Stop-hook exit 2 to non-blocking
    when stdout is empty and stderr looks like a missing-file error, and a
    non-empty stdout makes that branch unreachable.
    """
    print(json.dumps({"systemMessage":
                      f"announced_work_guard {VERSION}: Stop envelope drift — {why}. "
                      "The gate is not checking anything until this is fixed."}))
    print(DRIFT_MSG.format(v=VERSION, why=why), file=sys.stderr)
    return 2


class EnvelopeDrift(ValueError):
    """The Stop envelope no longer carries a message this guard can read.

    Raised for an unmodelled TYPE only. A field the runtime declares optional and
    legitimately omits is NOT drift - see message_text. What this catches is a
    renamed field or an alien shape, either of which would make the gate pass every turn,
    forever, while reading as a healthy hook. The house pattern in
    askq_timeout_guard separates UNRECOGNISED (schema changed) from
    OUT_OF_SCOPE (legitimately not ours), and only the first is loud.

    Drift blocks ONCE. `stop_hook_active` is true on the retry, so the guard
    returns success and the turn ends — the operator sees it, and a genuinely
    dead field costs one turn rather than wedging the session.
    """


def message_text(payload):
    """The last assistant message as plain text, however it is shaped."""
    if not isinstance(payload, dict):
        raise EnvelopeDrift(f"stdin parsed to {type(payload).__name__}, expected a JSON object")
    # ABSENT IS NOT DRIFT, BUT RENAMED STILL IS, and absence alone cannot tell
    # them apart. The 2.1.234 Stop schema declares
    # `last_assistant_message: F().optional()` and the runtime omits it whenever
    # the final assistant message carries no text block - so raising on a missing
    # key fired the loudest message in this file at a conformant envelope. Simply
    # allowing instead reopens the silent pass the file was written to stop, since
    # a rename also presents as absence. The discriminator is a LOOKALIKE key: the
    # field going missing is normal, the field going missing while something
    # message-shaped sits beside it is a schema change.
    if "last_assistant_message" not in payload:
        lookalike = [k for k in payload
                     if isinstance(k, str) and k != "last_assistant_message"
                     and re.search(r"assistant.*message|message.*assistant", k, re.I)]
        if lookalike:
            raise EnvelopeDrift(
                f"no 'last_assistant_message', but {lookalike[0]!r} is present — "
                "the Stop payload schema was renamed, not merely omitted")
        return ""            # declared-optional and legitimately absent
    m = payload.get("last_assistant_message")
    if isinstance(m, str):
        return m
    if isinstance(m, dict):
        c = m.get("content")
        if isinstance(c, str):
            return c
        if isinstance(c, list):
            return "\n".join(b.get("text", "") for b in c
                             if isinstance(b, dict) and b.get("type") == "text")
    if isinstance(m, list):
        return "\n".join(b.get("text", "") for b in m
                         if isinstance(b, dict) and b.get("type") == "text")
    if m is None:
        return ""            # present and empty is a real, readable state
    raise EnvelopeDrift(f"last_assistant_message is a {type(m).__name__}, "
                        f"not str/dict/list — shape changed")


def judge(payload):
    """-> trigger string to block on, or None to allow."""
    if isinstance(payload, dict) and payload.get("stop_hook_active"):
        return None                     # documented loop guard; never re-block
    text = message_text(payload).strip()
    if not text:
        return None                     # nothing read is not evidence of a defect
    units = boundary(text)
    tail = "\n".join(units)
    # A turn that ends on a QUESTION is asking, not claiming — whatever was
    # said before it. Found on a real transcript: a message opening "Starting
    # with a mechanical producer-existence check" and closing "Does the
    # fifth-entity model look right to you before I write any of it?" blocked,
    # which would have punished the exact behaviour the rule wants.
    if text.rstrip().endswith("?"):
        return None
    # Only the LAST unit decides. A handback in the penultimate unit that an
    # announcement then supersedes is not how the turn ends.
    if units and HANDBACK.search(units[-1]):
        return None
    m = ANNOUNCE.search(tail)
    return m.group(0).strip() if m else None


def armed(payload):
    """Live background work the runtime reports in the Stop envelope.

    `background_tasks` and `session_crons` are documented Stop fields - the
    binary's own words are that they let a hook "distinguish 'session is done'
    from 'session is paused waiting for background work to wake it'". This guard
    is exactly that distinction. Each entry carries an `id`, which is the handle
    TaskStop needs; without it the model can see a task in no query surface it
    has, and will report an empty result as proof of absence.

    Absent or malformed is treated as empty, NOT as drift: unlike
    last_assistant_message these are optional by declaration, and a session with
    nothing in flight legitimately sends `[]`.
    """
    out = []
    if not isinstance(payload, dict):
        return out
    for key in ("background_tasks", "session_crons"):
        rows = payload.get(key)
        if not isinstance(rows, list):
            continue
        for row in rows:
            if not isinstance(row, dict):
                continue
            if str(row.get("status", "")).lower() in ("completed", "failed", "cancelled",
                                                     "stopped", "killed"):
                continue                # terminal; TaskStop would reject it anyway
            out.append((key, row))
    return out


def contradicted(payload):
    """-> (claim, live_rows) when the ending denies in-flight work that exists.

    Kept OUT of judge() on purpose. judge() is text-only, which is what a
    transcript can support, so --sweep measures the same function it reports on.
    This check needs the envelope and therefore cannot be swept - saying so is
    cheaper than a measurement nobody can reproduce.
    """
    if isinstance(payload, dict) and payload.get("stop_hook_active"):
        return None
    live = armed(payload)
    if not live:
        return None                     # no claim can contradict an empty set
    text = message_text(payload).strip()
    if not text:
        return None
    tail = "\n".join(boundary(text))
    m = QUIESCENT.search(tail)
    if not m:
        return None
    if QUALIFIED.search(tail[m.start():m.start() + 90]):
        return None                     # a named exception is an honest report
    return m.group(0).strip(), live


def selftest():
    cases = [
        ("real violation, session 2026-08-12",
         {"last_assistant_message": "…needs the finding corrected, not the corpus.\n\n"
                                    "Starting the IR-38 audit."}, True),
        ("real violation, the other one",
         {"last_assistant_message": "Still worth doing while the mapping is in hand, "
                                    "but it's tidying, not repair.\n\nProceeding with step 3."}, True),
        ("handback is not a violation",
         {"last_assistant_message": "That one needs a decision. Next step is the "
                                    "propagation batch — say go and I'll start."}, False),
        ("plain report is not a violation",
         {"last_assistant_message": "Committed 19c57aa. 14 gates green, 56 of 88 fixed."}, False),
        ("announcement mid-message, work then done, is not a violation",
         {"last_assistant_message": "Let me check the register. …I checked it: 47 markers, "
                                    "all bound. Committed d5e1a26."}, False),
        ("loop guard: never block twice",
         {"last_assistant_message": "Starting the audit.", "stop_hook_active": True}, False),
        ("empty message is not a verdict",
         {"last_assistant_message": ""}, False),
        ("content-block shape parses",
         {"last_assistant_message": {"content": [{"type": "text", "text": "On it."}]}}, True),

        # Structural endings. Every one of these blocked under the first two
        # designs; messages here end in a table more often than in a sentence,
        # so a gate that fires on them is a gate the reader learns to ignore.
        ("ends in a table",
         {"last_assistant_message": "Let me check the register first.\n\n"
                                    "| gate | state |\n|---|---|\n| residue | green |"}, False),
        ("ends in a bullet list",
         {"last_assistant_message": "I'll run the audit and report.\n\n"
                                    "- F20 live\n- F90 live"}, False),
        ("ends in a code fence",
         {"last_assistant_message": "Let me look at the hook.\n\n"
                                    "```python\nx = 1\n```"}, False),
        ("ends in a numbered list",
         {"last_assistant_message": "Let me start on the batch.\n\n"
                                    "1. F20\n2. F90"}, False),
        ("ends in a heading",
         {"last_assistant_message": "Let me dig in.\n\n## What I found\n\n### Detail"}, False),

        # No punctuation anywhere must still be judged, or the shortest and
        # bluntest form of the failure is the one that walks through.
        ("bare announcement, no punctuation at all",
         {"last_assistant_message": "Starting the audit"}, True),
        ("announcement trailing into one long unpunctuated clause",
         {"last_assistant_message": "Starting the IR-38 audit and I expect it will take "
                                    "a while because there are seven claims"}, True),
        ("a question is a handback, not an announcement",
         {"last_assistant_message": "Should I start the audit?"}, False),
        ("handback wins even when an announcement appears earlier",
         {"last_assistant_message": "Starting sounds right. Let me know which you prefer."},
         False),

        # Verbatim from other projects' transcripts. Every one of these blocked
        # under the sentence-split design; three of the four were behaviour the
        # rule wants MORE of, which is how a gate teaches people to disable it.
        ("real FP: opens with an announcement, ends asking for approval",
         {"last_assistant_message": "Starting with a mechanical producer-existence check I can "
                                    "run against the schema block.\n\nDoes the fifth-entity model "
                                    "look right to you before I write any of it?"}, False),
        ("real FP: a standing policy about method, not imminent action",
         {"last_assistant_message": "I'll verify each agent's sharpest claim myself before it "
                                    "reaches you, as before."}, False),
        ("real FP: sequencing note, not a claim to be acting",
         {"last_assistant_message": "I'll audit R7-B against the register before starting it, "
                                    "per the order."}, False),
        ("real TP: same shape as the ones this was built for",
         {"last_assistant_message": "The preimage lint now tracks both and holds them "
                                    "consistent.\n\nContinuing with the merge class — currently "
                                    "the only entity that fits no merge class."}, True),
        ("`I'll` still fires when imminence is explicit",
         {"last_assistant_message": "That settles it. I'll now run the audit."}, True),
        # Measured misses. Real turn endings from the transcript corpus that the
        # `with|on|the|a|an` object slot allowed through; two carry `now`, the
        # strongest imminence marker there is. The third needs the rejoin as well.
        ("measured miss: demonstrative object",
         {"last_assistant_message": "That settles the ordering. Kicking off that "
                                    "research now."}, True),
        ("measured miss: named object",
         {"last_assistant_message": "No blockers. Starting Phase 1 - implementation "
                                    "in an isolated clone."}, True),
        ("measured miss: `to` object after a bolded unit",
         {"last_assistant_message": "...and bring the buy side with you.**\n\n"
                                    "Proceeding to the doc pass now."}, True),

        # The rejoin. SPLIT finds these boundaries and a space-join threw them away, so
        # an announcement after a list, table or heading lost the anchor ANNOUNCE needs.
        ("structure first, announcement last: bullets",
         {"last_assistant_message": "- F20 live\n- F90 live\n\n"
                                    "Starting the IR-38 audit."}, True),
        ("structure first, announcement last: table",
         {"last_assistant_message": "| gate | state |\n|---|---|\n| residue | green |"
                                    "\n\nStarting the IR-38 audit."}, True),
        ("structure first, announcement last: heading",
         {"last_assistant_message": "## What I found\n\nStarting the IR-38 audit."}, True),

        # HANDBACK decides on the LAST unit only. A handback an announcement then
        # supersedes is not how the turn ended.
        ("handback superseded by an announcement blocks",
         {"last_assistant_message": "Waiting on the two background agents. "
                                    "Starting the IR-38 audit."}, True),

        # ...and the arm keeping the background-work case allowed. Admitting `to` into
        # the object slot is what makes `Continuing to wait` reachable at all, so this
        # control only has teeth once that widening exists. Both must hold together.
        ("background wait still allows, one unit",
         {"last_assistant_message": "Continuing to wait on the two background "
                                    "agents."}, False),
        ("background wait still allows, after a report",
         {"last_assistant_message": "The batch is out. Continuing to monitor the "
                                    "three agents."}, False),

        # FALSE-POSITIVE CEILING. Verbatim corpus endings that a matcher without the
        # positional anchor blocks. The comment above calls position the whole
        # discriminator and nothing asserted it: deleting the anchor moved the measured
        # block count from 14 to 55 with every other control still green. These are
        # reports of work in flight, not claims to be starting it.
        ("FP ceiling: status report naming a running agent",
         {"last_assistant_message": "Six green, `design-candidate` still running "
                                    "the sweep."}, False),
        ("FP ceiling: report of what another agent is running",
         {"last_assistant_message": "The wp7-drafter is still running on the B5+B6 "
                                    "draft; I will report when it delivers."}, False),
        ("FP ceiling: `on it` inside a sentence about waiting",
         {"last_assistant_message": "If it does not answer shortly I will re-run those "
                                    "three questions myself rather than wait on it."}, False),
    ]
    cases += [
        # Envelope drift. Silently allowing here would make the gate pass every
        # turn forever while reading as a healthy hook - the exact
        # unvalidated-instrument failure the rest of this harness exists to
        # stop. Each of these must be LOUD, and each blocks only once.
        ("a renamed field is still drift — a lookalike key sits beside the gap",
         {"hook_event_name": "Stop", "assistant_message": "Starting the audit."}, "drift"),
        ("...and the rename is caught whatever the lookalike is called",
         {"hook_event_name": "Stop", "assistantMessageLast": "Starting the audit."}, "drift"),
        ("absent field is a declared-optional state, not drift",
         {"hook_event_name": "Stop", "session_id": "x"}, False),
        ("drift: the message is an alien shape",
         {"last_assistant_message": 42}, "drift"),
        ("drift: stdin is not an object",
         ["Starting the audit."], "drift"),
        ("drift blocks ONCE, not forever",
         {"stop_hook_active": True, "session_id": "x"}, False),
        ("present-but-null is a readable state, not drift",
         {"last_assistant_message": None}, False),
    ]
    # The contract, checked against a REAL captured Stop event rather than
    # against my reading of the binary. Absence is a failure, not a skip: a
    # missing fixture would quietly retire the only evidence that this guard
    # reads a field the runtime actually sends.
    fx = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "fixtures_stop", "S1_stop_real_envelope.json")
    try:
        real = json.load(open(fx, encoding="utf-8"))
    except Exception:
        real = None
    fx2 = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "fixtures_stop", "S2_stop_background_tasks.json")
    try:
        live = json.load(open(fx2, encoding="utf-8"))
    except Exception:
        live = None
    live_row = ((live or {}).get("background_tasks") or [{}])[0]
    cases += [
        ("real envelope: fixture present and parses",
         {"__contract__": real is not None}, "contract"),
        ("real envelope: last_assistant_message is a str",
         {"__contract__": isinstance((real or {}).get("last_assistant_message"), str)},
         "contract"),
        ("real envelope: stop_hook_active is a bool",
         {"__contract__": isinstance((real or {}).get("stop_hook_active"), bool)},
         "contract"),
        ("real envelope: hook_event_name is Stop",
         {"__contract__": (real or {}).get("hook_event_name") == "Stop"}, "contract"),
        ("real envelope, benign message -> allow", real if real else {"__contract__": False},
         False if real else "contract"),
        ("real envelope, announcement substituted -> block",
         dict(real, last_assistant_message="Right. Starting the IR-38 audit.")
         if real else {"__contract__": False}, True if real else "contract"),

        # S1 carries both arrays EMPTY, which proves the keys exist and nothing
        # more. S2 is the other half: a live backgrounded task, captured from a
        # real 2.1.234 Stop event. Absence is a failure, not a skip.
        ("live envelope: fixture present and parses",
         {"__contract__": live is not None}, "contract"),
        ("live envelope: background_tasks is a NON-EMPTY list",
         {"__contract__": isinstance((live or {}).get("background_tasks"), list)
          and len((live or {}).get("background_tasks") or []) > 0}, "contract"),
        ("live envelope: the entry carries a string id for TaskStop",
         {"__contract__": isinstance(live_row.get("id"), str) and bool(live_row.get("id"))},
         "contract"),
        ("live envelope: the entry reports a non-terminal status",
         {"__contract__": live_row.get("status") == "running"}, "contract"),
        ("live envelope: session_crons is a list",
         {"__contract__": isinstance((live or {}).get("session_crons"), list)}, "contract"),
        ("live envelope, benign ending -> allow",
         live if live else {"__contract__": False}, False if live else "contract"),
        ("live envelope, all-clear substituted -> block",
         dict(live, last_assistant_message="It is spinning on its own. Nothing is "
                                           "running. Nothing to wait for.")
         if live else {"__contract__": False}, True if live else "contract"),

        # The contradiction arm, hand-built so each discriminator has its own row.
        ("all-clear while a shell task runs",
         {"last_assistant_message": "Nothing is running. Nothing to wait for.",
          "background_tasks": [{"id": "b6zq8li65", "type": "shell", "status": "running",
           "description": "Sleep 45 seconds in background"}]}, True),
        ("all-clear while a cron is scheduled",
         {"last_assistant_message": "Nothing pending on my side.",
          "session_crons": [{"id": "c1", "type": "cron", "status": "scheduled",
                             "description": "loop"}]}, True),
        ("the same all-clear with nothing armed is honest",
         {"last_assistant_message": "Nothing is running. Nothing to wait for.",
          "background_tasks": [], "session_crons": []}, False),
        ("a denial that names its exception is a report, not an all-clear",
         {"last_assistant_message": "Nothing running except the two agents.",
          "background_tasks": [{"id": "b6zq8li65", "type": "shell", "status": "running",
           "description": "Sleep 45 seconds in background"}]}, False),
        ("live work with no all-clear is the ordinary case",
         {"last_assistant_message": "Committed c0a9739. Three agents still working.",
          "background_tasks": [{"id": "b6zq8li65", "type": "shell", "status": "running",
           "description": "Sleep 45 seconds in background"}]}, False),
        ("a terminal task cannot be contradicted - TaskStop would reject it",
         {"last_assistant_message": "Nothing is running.",
          "background_tasks": [{"id": "x", "type": "shell", "status": "completed"}]}, False),
        ("loop guard clears the contradiction too, not just the announcement",
         {"stop_hook_active": True,
          "last_assistant_message": "Nothing is running.",
          "background_tasks": [{"id": "b6zq8li65", "type": "shell", "status": "running",
           "description": "Sleep 45 seconds in background"}]}, False),
        ("a malformed background_tasks is empty, not drift",
         {"last_assistant_message": "Nothing is running.",
          "background_tasks": "not-a-list"}, False),
    ]

    # ENTRY-PATH CONTROLS. Every case above enters at judge() or contradicted();
    # main() was reachable from no test at all, and main() is where the wiring-
    # visible behaviour lives - the exit codes settings.json depends on, the
    # event-scope filter, the stdin read, and the kill switch. askq_timeout_guard
    # drives its own process for exactly this reason. Env is scrubbed of the kill
    # switch so an ambient value cannot make the suite pass, which is the same
    # precaution askq takes.
    failures = 0
    me = os.path.abspath(__file__)
    base_env = dict(os.environ)
    base_env.pop("ANNOUNCED_WORK_GUARD", None)
    BG = [{"id": "b6zq8li65", "type": "shell", "status": "running"}]
    proc_cases = [
        ("process: benign ending exits 0",
         {"hook_event_name": "Stop", "last_assistant_message": "Committed 19c57aa."}, None, 0),
        ("process: announcement exits 2",
         {"hook_event_name": "Stop", "last_assistant_message": "Right. Starting the audit."},
         None, 2),
        ("process: all-clear over live work exits 2",
         {"hook_event_name": "Stop", "last_assistant_message": "Nothing is running.",
          "background_tasks": BG}, None, 2),
        ("process: absent last_assistant_message is not a defect",
         {"hook_event_name": "Stop", "stop_hook_active": False, "session_id": "x"}, None, 0),
        ("process: a foreign hook event is out of scope",
         {"hook_event_name": "PreToolUse", "last_assistant_message": "Starting the audit."},
         None, 0),
        ("process: a crash BLOCKS rather than ending the turn",
         {"hook_event_name": "Stop",
          "last_assistant_message": {"content": [{"type": "text", "text": 123}]}}, None, 2),
        ("process: the kill switch is honoured",
         {"hook_event_name": "Stop", "last_assistant_message": "Right. Starting the audit."},
         {"ANNOUNCED_WORK_GUARD": "off"}, 0),
        ("process: the kill switch is exact-string, not truthy",
         {"hook_event_name": "Stop", "last_assistant_message": "Right. Starting the audit."},
         {"ANNOUNCED_WORK_GUARD": "1"}, 2),
    ]
    for name, payload, extra_env, want_code in proc_cases:
        env = dict(base_env)
        if extra_env:
            env.update(extra_env)
        p = subprocess.run([sys.executable, me], input=json.dumps(payload).encode(),
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env)
        ok = p.returncode == want_code
        if not ok:
            failures += 1
        print(f"  {'PASS' if ok else 'FAIL'} {name} -> exit {p.returncode}")
    # stdin that is not JSON at all, fed as raw bytes
    p = subprocess.run([sys.executable, me], input=b"not json",
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=base_env)
    ok = p.returncode == 2
    if not ok:
        failures += 1
    print(f"  {'PASS' if ok else 'FAIL'} process: non-JSON stdin blocks -> exit {p.returncode}")
    # --sweep over nothing is an error, not a clean 0.00%. The house rule is
    # already implemented twice: askq_timeout_guard exits 2 on zero fixtures, and
    # C6 fails when its scan set shrinks. This tool published a rate a reviewer is
    # invited to re-run, so a wrong glob printing a healthy 0% is the failure.
    p = subprocess.run([sys.executable, me, "--sweep", "/nonexistent-scan-set/*.jsonl"],
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=base_env)
    ok = p.returncode == 2 and b"scan set is empty" in p.stderr
    if not ok:
        failures += 1
    print(f"  {'PASS' if ok else 'FAIL'} process: --sweep over an empty scan set is an error "
          f"-> exit {p.returncode}")
    proc_n = len(proc_cases) + 2

    for name, payload, want in cases:
        if isinstance(payload, dict) and "__contract__" in payload:
            got = "contract" if payload["__contract__"] else "BROKEN"
            if got != want:
                failures += 1
            print(f"  {'PASS' if got == want else 'FAIL'} {name} -> {got}")
            continue
        try:
            got = (judge(payload) is not None) or (contradicted(payload) is not None)
        except EnvelopeDrift:
            got = "drift"
        if got != want:
            failures += 1
        label = got if isinstance(got, str) else ("block" if got else "allow")
        print(f"  {'PASS' if got == want else 'FAIL'} {name} -> {label}")
    print(f"\n  selftest: {failures} failure(s)")
    print(f"SELFTEST-SUMMARY suite=announced_work_guard "
          f"checks={len(cases) + proc_n} failures={failures}")
    return failures == 0


def corpus_identity(files):
    """A fingerprint of the scan set, so a re-run can tell drift from disagreement.

    The rate this tool prints is offered IN PLACE of a checkable literal, and that
    only works if a reviewer can tell "the matcher changed" from "the corpus
    changed". It could not: `~/.claude/projects` is a rolling window - the oldest
    surviving transcript here is 29 days old - so a stated rate stops reproducing
    within days while the command that produced it still runs clean. Print the
    corpus with the number and the two are distinguishable.
    """
    h = hashlib.sha256()
    oldest = newest = None
    for f in files:
        try:
            st = os.stat(f)
        except OSError:
            continue
        h.update(f"{os.path.basename(f)}:{st.st_size}".encode())
        oldest = st.st_mtime if oldest is None else min(oldest, st.st_mtime)
        newest = st.st_mtime if newest is None else max(newest, st.st_mtime)
    span = ""
    if oldest is not None:
        day = 86400.0
        span = (f" oldest={time.strftime('%Y-%m-%d', time.localtime(oldest))}"
                f" newest={time.strftime('%Y-%m-%d', time.localtime(newest))}"
                f" span_days={int((newest - oldest) / day)}")
    return f"files={len(files)} digest={h.hexdigest()[:16]}{span}"


def sweep(globs):
    """Re-run the false-positive measurement over real transcripts.

    A rate is worthless as a literal: nobody can check it and it drifts the moment
    either the matcher or the corpus changes. This is the query that regenerates
    it, printed with a corpus identity so a reviewer can tell which of the two
    moved. Earlier revisions of this file quoted bare figures - 6 blocks in 2676
    turns, 10 false positives across 696 transcripts - that no command reproduces,
    because the matcher they described is gone. Do not add another.

    A turn is scored only when it ENDS on text. Two exclusion classes get there,
    not one, and both are printed: a turn whose last text is followed by a tool
    call is the healthy case by construction, and a turn with no text block at all
    cannot exhibit the defect either. Reporting only the first understated the
    second by roughly a quarter of the excluded set.

    Only the text-only check is swept. The envelope check in contradicted() needs
    `background_tasks`, which no transcript carries, so it is not measured here -
    saying that is cheaper than a number nobody can reproduce.
    """
    import glob as _glob
    files = sorted({f for g in globs for f in _glob.glob(os.path.expanduser(g))})
    if not files:
        print(f"# COVERAGE {corpus_identity(files)}")
        print("# FATAL: the scan set is empty. Zero inputs is an error, never a clean "
              "verdict — a 0.00% rate over nothing reads identical to 0.00% over a "
              "corpus. Check the glob.", file=sys.stderr)
        return 2
    turns_n = ends = blocks = no_text = trailing_tool = 0
    hits = []
    for path in files:
        turns, cur, closed_by = [], [], []
        try:
            lines = open(path, encoding="utf-8", errors="replace").readlines()
        except OSError:
            continue
        for line in lines:
            try:
                d = json.loads(line)
            except ValueError:
                continue
            if d.get("isSidechain"):
                continue                        # subagent, not this turn
            c = (d.get("message") or {}).get("content")
            if d.get("type") == "user":
                # a user record carrying tool_result is the harness replying,
                # not a human turn boundary
                if isinstance(c, list) and any(
                        isinstance(b, dict) and b.get("type") == "tool_result" for b in c):
                    continue
                if cur:
                    turns.append(cur)
                    closed_by.append("meta" if d.get("isMeta") else "human")
                    cur = []
                continue
            if d.get("type") == "assistant" and isinstance(c, list):
                for b in c:
                    if isinstance(b, dict) and b.get("type") in ("text", "tool_use"):
                        cur.append((b["type"], b.get("text", "") or b.get("name", ""),
                                    d.get("timestamp") or ""))
        if cur:
            turns.append(cur)
            closed_by.append("eof")
        turns_n += len(turns)
        for t, closer in zip(turns, closed_by):
            li = max((i for i, (k, _, _) in enumerate(t) if k == "text"), default=None)
            if li is None:
                no_text += 1
                continue
            if any(k == "tool_use" for k, _, _ in t[li + 1:]):
                trailing_tool += 1
                continue
            ends += 1
            try:
                trig = judge({"last_assistant_message": t[li][1]})
            except EnvelopeDrift:
                continue
            if trig:
                blocks += 1
                hits.append((os.path.basename(os.path.dirname(path))[-30:],
                             os.path.basename(path)[:8], (t[li][2] or "")[:19], closer,
                             trig, " ".join(t[li][1][-260:].split())))
    print(f"# COVERAGE {corpus_identity(files)}")
    print(f"#   turns={turns_n} ending_on_text={ends} "
          f"excluded_no_text={no_text} excluded_trailing_tool={trailing_tool}")
    print("#   NOT COVERED: a turn ending in a tool call cannot exhibit this defect, and a "
          "turn with no text block cannot either. Both are excluded, so this is a rate over "
          "CANDIDATES, not over turns.")
    print("#   NOT COVERED: the envelope check in contradicted(). No transcript carries "
          "background_tasks, so its rate is unmeasured rather than zero.")
    print("#   NOT COVERED: whether each block is a TRUE positive. That is a human read; "
          "each hit prints its session, timestamp and what closed the turn so it can be "
          "disagreed with — a turn closed by `meta` was ended by a harness injection such "
          "as a background-agent report, which is a class the matcher is tuned around.")
    print(f"\n# {blocks} block(s) / {ends} candidates = "
          f"{100 * blocks / max(ends, 1):.2f}%\n")
    for proj, sess, ts, closer, trig, tail in hits:
        print(f"  [{proj}] {sess} {ts} closed_by={closer} {trig!r}")
        print(f"     …{tail}")
    return 0


def main(argv):
    if "--selftest" in argv:
        return 0 if selftest() else 1
    if "--sweep" in argv:
        rest = argv[argv.index("--sweep") + 1:]
        return sweep(rest or ["~/.claude/projects/*/*.jsonl"])
    off = os.environ.get("ANNOUNCED_WORK_GUARD") == "off"
    try:
        raw = sys.stdin.read()
        payload = json.loads(raw)
    except Exception as exc:
        if off:
            return 0
        return report_drift(f"stdin is not JSON ({exc})")
    if isinstance(payload, dict) and \
            payload.get("hook_event_name") not in (None, "Stop"):
        # SubagentStop is deliberately NOT in scope. It is registered nowhere, has
        # no fixture and no control, and one agent-teardown call site sends no
        # message at all while hard-coding stop_hook_active false - so the
        # once-only promise would not hold there. Accepting an event on those
        # terms is a claim with no evidence behind it.
        return 0                        # out of scope, which is not drift
    try:
        stale = contradicted(payload)
        trigger = judge(payload)
    except EnvelopeDrift as exc:
        if off:
            return 0
        return report_drift(str(exc))
    if off:
        return 0
    if stale:
        claim, live = stale
        rows = "\n".join(
            f"  {key}: id={row.get('id')!r} type={row.get('type')!r} "
            f"status={row.get('status')!r} {row.get('description') or ''}".rstrip()
            for key, row in live)
        print(STALE_MSG.format(v=VERSION, claim=claim, rows=rows), file=sys.stderr)
        return 2
    if not trigger:
        return 0
    print(BLOCK_MSG.format(v=VERSION, trigger=trigger), file=sys.stderr)
    return 2


if __name__ == "__main__":
    # A crash must BLOCK, not pass. Exit 1 is filed by the runtime as a
    # non-blocking error: the turn ends, the model is told nothing, and the only
    # operator signal is a toast byte-identical to the one a SUCCESSFUL block
    # produces - so it carries no information. Measured end to end against a
    # must-block control. askq_timeout_guard already converts a crash to exit 2;
    # this file did not, and no control asserted that it should.
    try:
        sys.exit(main(sys.argv))
    except SystemExit:
        raise
    except BaseException:
        sys.stderr.write(f"announced_work_guard {VERSION} CRASHED — blocking rather "
                         f"than letting the turn end on an unread envelope.\n"
                         f"{traceback.format_exc()}")
        sys.exit(2)
