#!/usr/bin/env python3
"""announced_work_guard — Claude Stop gate on ending with work announced, not done.

The failure it mechanizes, measured rather than imagined. In one long session
(2026-08-12, 314 turns) seven turns ended on a present-tense claim of work in
progress — "Starting the IR-38 audit.", "Proceeding with step 3." — with zero
tool calls after the sentence. Nothing had started. Asked how often, the model
audited itself and reported TWO. The real number was seven.

That gap is the point. This is not a diligence problem, it is a self-report
problem: an announcement is generated by the same fluent process as everything
else, so it reads identical whether or not the thing happened, and the model
cannot tell from the inside. The user's words: "I can't always babysit that."

The house rule this makes mechanical is AGENTS.md's: verification authority
lives outside the model, and a claim needs evidence checked at the same scope.
A claim about MY OWN execution is not exempt, and it is the one claim I had
never gated.

WHY A STOP HOOK IS THE RIGHT SEAM. At Stop the turn is already ending, so by
construction nothing can run after the final text. The check therefore needs no
transcript walk and no turn segmentation: if the last thing said announces
imminent action, that action is not going to happen.

WHAT THIS CANNOT DO. It reads the tail of one message. It cannot tell a
sincere announcement from a rhetorical one, it cannot catch work promised in
the middle of a message and quietly dropped, and it says nothing about whether
the work that DID run was any good. It anchors on a unit start, `.!?;`, a line
break, or an em dash. A colon is not an anchor, so `Next: I'll now run the
sweep.` is not seen -- making it one also blocks `Background: Running the sweep
in eight shards.` A colon followed by a LINE BREAK is still an anchor, because
the break is; that asymmetry is in the anchor set, not in a rule about colons.
Blocking here costs one turn; missing costs the user's trust in every status
line, which is why it is tuned to fire.

CONTRACT, VERIFIED THREE WAYS rather than read once. (1) In-binary against
Claude Code 2.1.227. (2) Against a REAL captured Stop envelope, shipped as
hooks/fixtures_stop/S1_stop_real_envelope.json and asserted field-by-field in the
selftest — `last_assistant_message` is a plain str, `stop_hook_active` a bool.
(3) End to end in a live headless session: a run told to answer "Starting the
audit." was blocked at Stop, received this guard's message, and rewrote its
ending to "no work was performed, no tools were run, and nothing is pending".
The measurement behind the tuning is re-runnable, not a literal:
`announced_work_guard.py --sweep` regenerates it over any transcript glob.

Stop hooks receive
{"hook_event_name": "Stop", "stop_hook_active": bool,
 "last_assistant_message": ..., "session_id", "transcript_path", ...}.
Exit 2 blocks the stop and returns stderr to the model. `stop_hook_active` is
the documented loop guard — the binary warns "check stop_hook_active in the
input and return success while it's true" and caps consecutive blocks
(CLAUDE_CODE_STOP_HOOK_BLOCK_CAP).

    python3 ~/.claude/hooks/announced_work_guard.py            # as a hook
    python3 ~/.claude/hooks/announced_work_guard.py --selftest # controls

Exit codes: 0 allow (no announcement, or out of scope) · 2 block, with the
reason on stderr · 1 selftest failure.
"""
import json
import os
import re
import subprocess
import sys
from collections import deque

VERSION = "1.0.0"

# An announcement of imminent action BY ME, anchored to the TAIL of the final
# message. The same words mid-message are ordinary narration of work that then
# happens; only at the boundary do they become a claim with nothing behind it.
ANNOUNCE = re.compile(
    # NOT `-\s*` in the prefix: it matched the hyphen inside `long-running`
    # and fired on five turns across three projects that never announced
    # anything. Em-dash is a real clause lead; hyphen is part of a word.
    # `;` joins two independent clauses, so it ends a claim the way a full stop does.
    # `:` does NOT: it labels what follows, and `Background: Running the sweep in eight
    # shards.` is a report on work already running -- the same carve-out the participle
    # arm makes for `Continuing to wait`. A colon-led announcement is therefore out of
    # scope and said so below, rather than bought at the price of that shape.
    # `--` as well as the em dash: it is this repository's own spelling for one, in every
    # context file and commit message, and only the typographic character was modelled.
    r'(?:^|[.!?;\n]\s*|—\s*|--\s+)'
    r'(?:'
    # The participle must lead into an OBJECT — "Starting the audit",
    # "Continuing with the merge class". `Continuing to wait/collect/hold` is a
    # description of an ongoing state, usually while background agents run, and
    # ending the turn there is correct. That distinction is 4 of the 10 false
    # positives measured across 696 transcripts.
    r'(?:Starting|Running|Proceeding|Continuing|Beginning|Kicking off|Firing off)'
    r'\s+(?:with|on|the|a|an)\b'
    r'|(?:Let me|Let\'s)\s+(?:now\s+|go\s+ahead\s+and\s+)?'
    r'(?:start|run|check|look|do|go|build|fix|verify|audit|dig|pull|open|read|grep|sweep|write|take)'
    # `I'll <verb>` REQUIRES an imminence marker. Bare "I'll verify X" is far
    # more often a standing policy or a sequencing note than a claim to be
    # acting now — measured on real transcripts, that arm produced 3 of 4 false
    # positives ("I'll verify each agent's sharpest claim myself, as before").
    # The present participles carry the failure on their own.
    r'|I\'?ll\s+(?:now|go\s+ahead\s+and)\s+'
    r'(?:start|run|check|look|do|build|fix|verify|audit|dig|pull|open|read|write|kick|take)'
    r'|(?:On it|Doing that now|Running that now|Starting now|Working on it)\b'
    r')',
    re.I)

# Legitimate ways to end a turn. These must never be blocked: handing the
# decision back is the correct move, and gating it would push the model toward
# acting without approval - the opposite failure, and a worse one.
# A participle clause whose sentence goes on to REPORT is narration of work that ran, not
# a claim that it is about to. `Running the sweep completed in 4m.` is the same opening
# words as the failure this blocks and the opposite meaning, and the decoration strip put
# that shape in reach for the first time. Matched only against the REST of the unit the
# trigger was found in, so a report in the following sentence cannot excuse an
# announcement in this one.
REPORT = re.compile(
    r'\b(?:completed|finished|took|landed|ran|passed|failed|produced|returned|wrote|'
    r'reproduced|stayed|showed|found)\b', re.I)

# A completed-work token is evidence only when it is the predicate of the activity that
# ANNOUNCE matched. The participle arm can form that grammatical subject; "Let me", "I'll"
# and the fixed-form arms cannot. Clause boundaries stop the association, so a prior run's
# result in "Starting the audit because the previous run failed" cannot excuse the new
# announcement. This remains an explicit English heuristic, not a general parser.
# The participle check is load-bearing: "Let me verify the checks passed earlier" has a
# completed-work token, a result tail, and no clause break, yet reports nothing about the
# proposed verification. Interrogative complements are also clause breaks, so they cannot
# be the shape that grades this test.
PARTICIPLE_ANNOUNCEMENT = re.compile(
    r'(?:Starting|Running|Proceeding|Continuing|Beginning|Kicking off|Firing off)'
    r'\s+(?:with|on|the|a|an)$', re.I)
REPORT_CLAUSE_BREAK = re.compile(
    r'[.!?;,](?=\s|$)|:(?=[ \t]+[A-Za-z])|—|(?<!\S)--(?=\s)|'
    r'\b(?:and|but|or|nor|so|yet|because|since|after|before|when|while|although|'
    r'though|whereas|if|unless|until|once|whether|what|why|where|how|which|who|whose|'
    r'that|then)\b',
    re.I)
REPORT_WORD = re.compile(r"[A-Za-z0-9][A-Za-z0-9_'/-]*")
REPORT_MODIFIERS = frozenset({
    "already", "earlier", "formerly", "last", "previously", "prior", "recently",
})
REPORT_NONFINAL = frozenset({
    "a", "an", "the", "of", "for", "with", "on", "in", "from", "to", "by",
    "against", "because", "since", "after", "before", "when", "while", "although",
    "though", "whereas", "if", "unless", "until", "once", "which", "who", "whose",
    "that", "and", "but", "or", "nor", "so", "yet", "not", "never",
})
REPORT_INCOMPLETE = frozenset({
    "will", "would", "shall", "should", "may", "might", "can", "could", "must",
    "being", "not", "never",
})
# These forms can modify a following noun: a count before "failed tests" is not a
# completed activity. Accept result tails and determiner/quantifier-led result objects,
# not an ambiguous bare following noun. "completed the migration" is a result predicate;
# "three completed migrations" still describes the object being announced.
# Other REPORT verbs retain their object-taking forms ("produced output", "took minutes").
# Block classification has already separated containers and paragraphs; wrapping inside
# the remaining prose unit must not change whether a predicate reports completed work.
REPORT_ADJECTIVAL = frozenset({"completed", "finished", "passed", "failed"})
# Matched with pattern.match(remainder, pos): the call anchors the attempt, so the
# pattern itself carries no ^ (which would refuse every nonzero position).
REPORT_RESULT_TAIL = re.compile(
    r'[*_]*(?:[ \t\r\n]*$|[.!?;,:)]|[ \t\r\n]+(?:in|at|on|by|after|before|during|with|'
    r'without|to|because|since|when|successfully|unsuccessfully|earlier|recently|'
    r'today|yesterday|again|a|an|the|this|that|these|those|all|both|each|every|any|'
    r'some|several|many|multiple|no|another|[0-9]+|zero|one|two|three|four|five|six|'
    r'seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|'
    r'eighteen|nineteen|twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)\b)', re.I)


def reports_this_activity(unit, found):
    """Return whether a direct completed-work predicate belongs to ``found``.

    One pass, linear in the unit. The clause-break search and the token state advance
    alongside the report matches instead of being recomputed over a growing prefix: this
    runs inside the registered five-second hook budget, and a rescanning shape let a
    thirty-kilobyte tail of report tokens time the guard out into an allow. A token that
    straddles the report match contributes no word state; between spaced words the two
    formulations read the same prefix.
    """
    if not PARTICIPLE_ANNOUNCEMENT.search(found.group(0)):
        return False
    remainder = unit[found.end():]
    token_iter = REPORT_WORD.finditer(remainder)
    token = next(token_iter, None)
    core_last = None          # last non-modifier token ending at or before the report
    core_incomplete = False   # an INCOMPLETE token seen among those
    # A full-string break match is verified against each report's own prefix (endpos),
    # because a lookahead may succeed only on characters past the cut: a colon before
    # "completed in 4m" is a label there, not a clause break. The one break a prefix can
    # see that the full string cannot is terminal punctuation directly at the cut, checked
    # per report in constant time.
    break_hint = REPORT_CLAUSE_BREAK.search(remainder)
    break_from = break_hint.start() if break_hint else None
    for report in REPORT.finditer(remainder):
        cut = report.start()
        # cut is positive: ANNOUNCE ends on a word character, so a report token cannot
        # begin at the remainder's first character without erasing its own boundary. The
        # cut operand guards the index anyway and is correctly unkillable.
        if cut and remainder[cut - 1] in ".!?;,":
            return False
        if (break_from is not None
                and REPORT_CLAUSE_BREAK.search(remainder, break_from, cut) is not None):
            return False
        # A report match is itself word characters, so it lies inside some token whose
        # end exceeds the cut; the iterator cannot exhaust while a report is pending, and
        # the None guard is correctly unkillable.
        while token is not None and token.end() <= cut:
            word = token.group(0).casefold()
            if word not in REPORT_MODIFIERS:
                # A determiner is inside ANNOUNCE, so the remainder must still name an
                # activity. This rejects "Starting the failed audit" and "Starting the
                # already completed audit"; a dangling preposition rejects "Starting the
                # audit for failed checks".
                core_last = word
                core_incomplete = core_incomplete or word in REPORT_INCOMPLETE
            token = next(token_iter, None)
        if core_last is None or core_last in REPORT_NONFINAL:
            continue
        if core_incomplete:
            continue
        if (report.group(0).casefold() in REPORT_ADJECTIVAL
                and not REPORT_RESULT_TAIL.match(remainder, report.end())):
            continue
        return True
    return False

HANDBACK = re.compile(
    r'(stopping here|stopped here|say go|your call|let me know|over to you|'
    r'waiting on|want me to|shall I|should I|do you want|which (would|do) you|'
    r'before I (start|proceed|continue|touch|change)|say the word|'
    r'happy to .{0,30}if you|unless you|if you\'d rather|continuing to (wait|collect|hold|monitor|poll|watch))', re.I)

# The boundary is the LAST SENTENCE OR TWO, not a character window. A window
# was the first design and its own control caught it: on a short message the
# window is the whole message, so "Let me check the register. …I checked it:
# 47 markers. Committed d5e1a26." blocked - an announcement that was narration
# of work the same message then reported doing. Position in the message is the
# whole discriminator, so it has to be measured in sentences.
TAIL_UNITS = 2

# Structural blocks are identified before sentence splitting. Each table row, heading,
# list item or paragraph supplies units; a fenced code block supplies exactly ONE unit,
# regardless of delimiter type, content punctuation or the presence of a closing line.
# Shown material still occupies tail slots, but cannot announce work. Code also cannot
# supply a handback. Inline emphasis is decoration, not a structural container.
SENTENCE_END = re.compile(r'(?<=[.!?])\s+')
EMPHASIS = re.compile(r'^(?:\*\*|__|\*|_)+')
QUOTE_LEAD = re.compile(r'^(?: {0,3}>[ \t]?)+')
QUOTE_MARKER = re.compile(r' {0,3}>[ \t]?')
LIST_LEAD = re.compile(r'^[ \t]*(?:[-+*]|\d+[.)])[ \t]+')
ATX_HEADING = re.compile(r'^[ \t]*#{1,6}(?=[ \t]|$)')
FENCE_LINE = re.compile(r'^ {0,3}(`{3,}|~{3,})(.*)$')


def markdown_blocks(text):
    """Yield the supported physical block spans as (text, code, container).

    Quote/list paragraphs admit marked, indented and lazy continuation lines; ATX
    headings and table rows end at their physical line. Blank lines end lazy continuation.
    List indentation can retain a following paragraph. A fence closes only on a matching
    kind, sufficient length and whitespace-only suffix, or at its containing block's end.
    This is a bounded block classifier, not a full Markdown parser: setext headings, HTML
    blocks, thematic breaks and standalone indented code are not classified here.
    """
    lines, kind = [], "prose"
    paragraph = False
    list_indent = 0
    fence = None

    def take():
        nonlocal lines
        block = "\n".join(lines)
        lines = []
        return block, kind == "code", kind != "prose"

    for raw in text.split("\n"):
        # CRLF framing is not a fence suffix. Keep the original block text unchanged.
        line = (raw[:-1] if raw.endswith("\r") else raw).expandtabs(4)
        quote = QUOTE_LEAD.match(line)
        depth = quote.group(0).count(">") if quote else 0
        content = line[quote.end():] if quote else line
        indent = len(content) - len(content.lstrip(" "))
        if fence:
            delimiter, length, quote_depth, fence_indent = fence
            offset = 0
            for _ in range(quote_depth):
                prefix = QUOTE_MARKER.match(line, offset)
                if not prefix:
                    break
                offset = prefix.end()
            # Strip only the opener's container prefix. Extra `>` characters inside code
            # are literal content, not a new quote whose marker can reveal a closer.
            content = line[offset:]
            indent = len(content) - len(content.lstrip(" "))
            if (depth < quote_depth
                    or (fence_indent and content.strip() and indent < fence_indent)):
                yield take()
                fence = None
                paragraph, list_indent = False, 0
            else:
                lines.append(raw)
                closer = FENCE_LINE.match(content[fence_indent:])
                if (closer and closer.group(1)[0] == delimiter
                        and len(closer.group(1)) >= length
                        and not closer.group(2).strip(" \t")):
                    yield take()
                    fence = None
                continue
        if not line.strip():
            if lines:
                yield take()
            paragraph = False
            continue

        indented_item = bool(list_indent and indent >= list_indent)
        if indented_item:
            content = content[list_indent:]
        item = LIST_LEAD.match(content)
        if item:
            list_indent = (list_indent if indented_item else 0) + item.end()
            content = content[item.end():]
            next_kind = "list"
        elif depth or indented_item:
            next_kind = "list" if indented_item else "quote"
        elif paragraph and kind in ("quote", "list"):
            next_kind = kind
        else:
            next_kind, list_indent = "prose", 0

        marker = FENCE_LINE.match(content)
        if marker and (marker.group(1)[0] != "`" or "`" not in marker.group(2)):
            if lines:
                yield take()
            kind, lines = "code", [raw]
            fence = (marker.group(1)[0], len(marker.group(1)), depth,
                     list_indent if item or indented_item else 0)
            paragraph = False
            continue
        if ATX_HEADING.match(content) or content.lstrip().startswith("|"):
            if lines:
                yield take()
            kind, lines = "container", [raw]
            yield take()
            paragraph = False
            if not item and not indented_item:
                list_indent = 0
            continue
        if item or kind != next_kind or not content.strip():
            if lines:
                yield take()
        kind = next_kind
        lines.append(raw)
        paragraph = bool(content.strip())
    if lines:
        yield take()


def boundary(text):
    """The last TAIL_UNITS units as (text, is_code, is_container).

    Work policy: classify physical lines once, split each non-code block once, and retain
    only two units. No sentence rescans or copies its growing physical-line prefix; no
    tail truncation can discard an earlier fence opener. The scale selftest checks this
    progress property separately from the actual-stdin five-second runtime probe.
    """
    parts = deque(maxlen=TAIL_UNITS)

    def append(part, container):
        unit = part.strip()
        if not container:
            unit = EMPHASIS.sub("", unit).strip()
        if unit:
            parts.append((unit, False, container))

    for block, code, container in markdown_blocks(text):
        if code:
            parts.append((block, True, container))
            continue
        cursor = 0
        for separator in SENTENCE_END.finditer(block):
            append(block[cursor:separator.start()], container)
            cursor = separator.end()
        append(block[cursor:], container)
    return list(parts)


BLOCK_MSG = """\
STOP BLOCKED — announced-work guard ({v}).

Your final sentence announces work you have not started: {trigger!r}

At Stop the turn is over, so nothing can run after it. As written this is a
status claim with no execution behind it, and the reader cannot tell the
difference from the outside. Measured base rate for this failure in one
session: 7 turns of 314, self-reported as 2.

Do exactly one of these, now:
  1. Make the tool calls. If you meant it, the calls belong in THIS turn.
  2. Rewrite the ending without the announcement — report what you DID (past
     tense, from tool output), then state the next step as a proposal:
     "next step is X, say go" or "stopping here".

Do not restate the intention in different words. That is the same claim."""

DRIFT_MSG = """\
STOP BLOCKED — announced-work guard ({v}) HAS GONE BLIND.

{why}

This guard reads `last_assistant_message` from the Stop envelope. It cannot
read this one, so it is not checking anything — and a checker that passes
because it read nothing is worse than no checker, because it still reads as
green. Blocking once so this is seen rather than silently inherited.

This is a HARNESS defect, not a defect in the turn. Fix
~/.claude/hooks/announced_work_guard.py against the current Stop contract, or
set ANNOUNCED_WORK_GUARD=off to disable it deliberately. The retry carries
stop_hook_active, so the turn will end normally and this will not loop."""


class EnvelopeDrift(ValueError):
    """The Stop envelope no longer carries a message this guard can read.

    Returning "allow" here is the failure this whole file exists to prevent: a
    renamed or dropped field would make the gate silently pass every turn,
    forever, while reading as a healthy hook. The house pattern in
    askq_timeout_guard separates UNRECOGNISED (schema changed) from
    OUT_OF_SCOPE (legitimately not ours), and only the first is loud.

    Drift blocks ONCE. `stop_hook_active` is true on the retry, so the guard
    returns success and the turn ends — the operator sees it, and a genuinely
    dead field costs one turn rather than wedging the session.
    """


def text_blocks(blocks):
    """Read supported text blocks without coercing malformed values into evidence."""
    parts = []
    for index, block in enumerate(blocks):
        if not isinstance(block, dict) or block.get("type") != "text":
            continue
        value = block.get("text", "")
        if not isinstance(value, str):
            raise EnvelopeDrift(f"text block {index} has {type(value).__name__} text, "
                                "expected str")
        parts.append(value)
    return "\n".join(parts)


def message_text(payload):
    """The last assistant message as plain text, however it is shaped."""
    if not isinstance(payload, dict):
        raise EnvelopeDrift(f"stdin parsed to {type(payload).__name__}, expected a JSON object")
    if "last_assistant_message" not in payload:
        raise EnvelopeDrift("envelope has no 'last_assistant_message' key — "
                            "the Stop payload schema changed")
    m = payload.get("last_assistant_message")
    if isinstance(m, str):
        return m
    if isinstance(m, dict):
        c = m.get("content")
        if isinstance(c, str):
            return c
        if isinstance(c, list):
            return text_blocks(c)
    if isinstance(m, list):
        return text_blocks(m)
    if m is None:
        return ""            # present and empty is a real, readable state
    raise EnvelopeDrift(f"last_assistant_message is a {type(m).__name__}, "
                        f"not str/dict/list — shape changed")


def judge(payload):
    """-> trigger string to block on, or None to allow."""
    if isinstance(payload, dict) and payload.get("stop_hook_active"):
        return None                     # documented loop guard; never re-block
    text = message_text(payload)
    if not text.strip():
        # An early return, not a guard: with it removed the empty string reaches boundary(),
        # matches neither pattern, and judge returns None anyway. Kept because it states the
        # intent -- nothing read is not evidence of a defect -- and a mutation of it is
        # correctly unkillable rather than an uncovered branch.
        return None
    units = boundary(text)
    # Code is excluded here too. Reading it let text inside a fence retract a real
    # announcement in the sentence above, which is the same mistake in the other direction.
    tail = " ".join(unit for unit, code, _container in units if not code)
    # A non-code tail that ends on a QUESTION is asking, not claiming — whatever was
    # said before it. Found on a real transcript: a message opening "Starting
    # with a mechanical producer-existence check" and closing "Does the
    # fifth-entity model look right to you before I write any of it?" blocked,
    # which would have punished the exact behaviour the rule wants.
    if tail.rstrip().endswith("?"):
        return None
    if HANDBACK.search(tail):
        return None
    # Searched per unit, because a unit's start is what ANNOUNCE's `^` alternative is for.
    # HANDBACK stays on the joined tail: handing the decision back in the following
    # sentence retracts an announcement in the one before it, which is the whole point of
    # reading two units rather than one.
    for unit, is_code, is_container in units:
        if is_code or is_container:
            continue
        for found in ANNOUNCE.finditer(unit):
            if not reports_this_activity(unit, found):
                return found.group(0).strip()
    return None


def selftest():
    cases = [
        ("real violation, session 2026-08-12",
         {"last_assistant_message": "…needs the finding corrected, not the corpus.\n\n"
                                    "Starting the IR-38 audit."}, True),
        ("real violation, the other one",
         {"last_assistant_message": "Still worth doing while the mapping is in hand, "
                                    "but it's tidying, not repair.\n\nProceeding with step 3."}, True),
        ("handback is not a violation",
         {"last_assistant_message": "That one needs a decision. Next step is the "
                                    "propagation batch — say go and I'll start."}, False),
        ("plain report is not a violation",
         {"last_assistant_message": "Committed 19c57aa. 14 gates green, 56 of 88 fixed."}, False),
        ("announcement mid-message, work then done, is not a violation",
         {"last_assistant_message": "Let me check the register. …I checked it: 47 markers, "
                                    "all bound. Committed d5e1a26."}, False),
        ("loop guard: never block twice",
         {"last_assistant_message": "Starting the audit.", "stop_hook_active": True}, False),
        ("empty message is not a verdict",
         {"last_assistant_message": ""}, False),
        ("content-block shape parses",
         {"last_assistant_message": {"content": [{"type": "text", "text": "On it."}]}}, True),

        # Structural endings. Every one of these blocked under the first two
        # designs; messages here end in a table more often than in a sentence,
        # so a gate that fires on them is a gate the reader learns to ignore.
        ("ends in a table",
         {"last_assistant_message": "Let me check the register first.\n\n"
                                    "| gate | state |\n|---|---|\n| residue | green |"}, False),
        ("ends in a bullet list",
         {"last_assistant_message": "I'll run the audit and report.\n\n"
                                    "- F20 live\n- F90 live"}, False),
        # A whole fenced block is one structural unit, so the preceding sentence is
        # still in the two-unit tail. Showing code does not itself retract that claim.
        ("one closed code block leaves the preceding announcement in the tail",
         {"last_assistant_message": "Let me look at the hook.\n\n"
                                    "```python\nx = 1\n```"}, True),
        ("ends in a numbered list",
         {"last_assistant_message": "Let me start on the batch.\n\n"
                                    "1. F20\n2. F90"}, False),
        ("ends in a heading",
         {"last_assistant_message": "Let me dig in.\n\n## What I found\n\n### Detail"}, False),

        # No punctuation anywhere must still be judged, or the shortest and
        # bluntest form of the failure is the one that walks through.
        ("bare announcement, no punctuation at all",
         {"last_assistant_message": "Starting the audit"}, True),
        ("announcement trailing into one long unpunctuated clause",
         {"last_assistant_message": "Starting the IR-38 audit and I expect it will take "
                                    "a while because there are seven claims"}, True),
        ("a question is a handback, not an announcement",
         {"last_assistant_message": "Should I start the audit?"}, False),
        ("handback wins even when an announcement appears earlier",
         {"last_assistant_message": "Starting sounds right. Let me know which you prefer."},
         False),

        # Verbatim from other projects' transcripts. Every one of these blocked
        # under the sentence-split design; three of the four were behaviour the
        # rule wants MORE of, which is how a gate teaches people to disable it.
        ("real FP: opens with an announcement, ends asking for approval",
         {"last_assistant_message": "Starting with a mechanical producer-existence check I can "
                                    "run against the schema block.\n\nDoes the fifth-entity model "
                                    "look right to you before I write any of it?"}, False),
        ("real FP: a standing policy about method, not imminent action",
         {"last_assistant_message": "I'll verify each agent's sharpest claim myself before it "
                                    "reaches you, as before."}, False),
        ("real FP: sequencing note, not a claim to be acting",
         {"last_assistant_message": "I'll audit R7-B against the register before starting it, "
                                    "per the order."}, False),
        ("real TP: same shape as the ones this was built for",
         {"last_assistant_message": "The preimage lint now tracks both and holds them "
                                    "consistent.\n\nContinuing with the merge class — currently "
                                    "the only entity that fits no merge class."}, True),
        ("`I'll` still fires when imminence is explicit",
         {"last_assistant_message": "That settles it. I'll now run the audit."}, True),
    ]
    failures = 0
    checks = 0
    cases += [
        # Envelope drift. Silently allowing here would make the gate pass every
        # turn forever while reading as a healthy hook - the exact
        # unvalidated-instrument failure the rest of this harness exists to
        # stop. Each of these must be LOUD, and each blocks only once.
        ("drift: the field is renamed",
         {"hook_event_name": "Stop", "assistant_message": "Starting the audit."}, "drift"),
        ("drift: the field is gone entirely",
         {"hook_event_name": "Stop", "session_id": "x"}, "drift"),
        ("drift: the message is an alien shape",
         {"last_assistant_message": 42}, "drift"),
        ("drift: stdin is not an object",
         ["Starting the audit."], "drift"),
        ("drift blocks ONCE, not forever",
         {"stop_hook_active": True, "session_id": "x"}, False),
        ("present-but-null is a readable state, not drift",
         {"last_assistant_message": None}, False),
    ]
    # The contract, checked against a REAL captured Stop event rather than
    # against my reading of the binary. Absence is a failure, not a skip: a
    # missing fixture would quietly retire the only evidence that this guard
    # reads a field the runtime actually sends.
    fx = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "fixtures_stop", "S1_stop_real_envelope.json")
    try:
        real = json.load(open(fx, encoding="utf-8"))
    except Exception:
        real = None
    cases += [
        ("real envelope: fixture present and parses",
         {"__contract__": real is not None}, "contract"),
        ("real envelope: last_assistant_message is a str",
         {"__contract__": isinstance((real or {}).get("last_assistant_message"), str)},
         "contract"),
        ("real envelope: stop_hook_active is a bool",
         {"__contract__": isinstance((real or {}).get("stop_hook_active"), bool)},
         "contract"),
        ("real envelope: hook_event_name is Stop",
         {"__contract__": (real or {}).get("hook_event_name") == "Stop"}, "contract"),
        ("real envelope, benign message -> allow", real if real else {"__contract__": False},
         False if real else "contract"),
        ("real envelope, announcement substituted -> block",
         dict(real, last_assistant_message="Right. Starting the IR-38 audit.")
         if real else {"__contract__": False}, True if real else "contract"),

        # Envelope shapes. message_text claims to read five, and only some were pinned. The
        # Stop payload's shape is not this repository's to fix, so each spelling it accepts
        # needs a case, or a host change silently stops the guard reading anything.
        ("shape: message as a bare string",
         {"last_assistant_message": "Starting the audit."}, True),
        ("shape: message as an object with string content",
         {"last_assistant_message": {"content": "Starting the audit."}}, True),
        ("shape: message as an object with a block list",
         {"last_assistant_message":
          {"content": [{"type": "text", "text": "Starting the audit."}]}}, True),
        ("shape: message as a bare block list",
         {"last_assistant_message": [{"type": "text", "text": "Starting the audit."}]}, True),
        ("shape: a non-text block contributes nothing",
         {"last_assistant_message": [{"type": "thinking", "text": "Starting the audit."}]},
         False),
        ("shape: a non-text block inside an object's block list contributes nothing",
         {"last_assistant_message":
          {"content": [{"type": "thinking", "text": "Starting the audit."}]}}, False),
        ("shape: a non-object entry in an object's block list is skipped",
         {"last_assistant_message": {"content": ["Starting the audit."]}}, False),
        ("shape: a non-object entry in a bare block list is skipped",
         {"last_assistant_message": ["Starting the audit."]}, False),
        ("shape: message present and null reads as empty",
         {"last_assistant_message": None}, False),
        ("shape: an unmodelled message type is drift, not an allow",
         {"last_assistant_message": 17}, "drift"),
        ("shape: a payload that is not an object is drift", "not an object", "drift"),

        # Markdown decoration on a unit's HEAD. Before units stopped being pre-joined,
        # the same sentence blocked
        # after a full stop and walked past behind two asterisks, a bullet or a caret.
        # These are the shapes this house writes its closing lines in.
        ("a bold announcement is still an announcement",
         {"last_assistant_message": "**Starting the IR-38 audit.**"}, True),
        # The other side of that split. A container holds material being SHOWN, and every
        # one of these was allowed before the strip existed; each is a shape this house
        # writes constantly, and three of them are behaviour the rule wants more of.
        ("a plan item is a proposal, not a claim that it started",
         {"last_assistant_message": "Remaining work:\n\n- Starting the IR-38 audit."}, False),
        ("a quoted log line is not the speaker's claim",
         {"last_assistant_message": "The log said:\n\n> Starting the audit at 07:31\n"
                                    "> Finished at 07:44"}, False),
        ("a section title is not a closing claim",
         {"last_assistant_message": "Done.\n\n## Running the sweep: results\n\nAll green."},
         False),
        ("a tilde fence is a fence",
         {"last_assistant_message": "Two items closed.\n\n~~~\n- Starting the audit\n~~~"},
         False),
        ("a fence inside a quote is still not a claim",
         {"last_assistant_message": "Quoting the log:\n\n> ```\n> Starting the audit\n"
                                    "> ```"}, False),
        ("an indented code block is not a claim",
         {"last_assistant_message": "Two items closed.\n\n    - Starting the audit"}, False),
        ("a verb-initial status bullet is not a claim",
         {"last_assistant_message": "Agents:\n\n- Running the sweep (F1)\n- idle (F2)"},
         False),
        ("a first-column table cell is not a claim",
         {"last_assistant_message": "| step | owner |\n|---|---|\n"
                                    "| Starting the audit | F1 |"}, False),
        # Structural identity belongs to the physical Markdown line, not only its first
        # sentence. Sentence splitting removes the marker from every later fragment unless boundary()
        # carries the line's classification beside it.
        ("a quote's second sentence remains quoted material",
         {"last_assistant_message": "> Log says safe. Starting the audit."}, False),
        ("a hyphen item's second sentence remains a plan item",
         {"last_assistant_message": "- Status note. Starting the audit."}, False),
        ("a plus item's second sentence remains a plan item",
         {"last_assistant_message": "+ Status note. Starting the audit."}, False),
        ("an asterisk item's first sentence is not emphasis",
         {"last_assistant_message": "* Starting the audit."}, False),
        ("an asterisk item's second sentence remains a plan item",
         {"last_assistant_message": "* Status note. Starting the audit."}, False),
        ("a numbered item's second sentence remains a plan item",
         {"last_assistant_message": "1. Status note. Starting the audit."}, False),
        ("a table cell's second sentence remains shown material",
         {"last_assistant_message": "| Status note. Starting the audit. |"}, False),
        ("a heading's second sentence remains a heading",
         {"last_assistant_message": "## Status note. Starting the audit."}, False),
        ("the same second sentence in prose remains an announcement",
         {"last_assistant_message": "Log says safe. Starting the audit."}, True),
        # A heading ends at its physical line; a quote/list paragraph can continue without
        # repeating the marker. The latter are CommonMark's lazy continuation lines.
        ("a heading ends at its line break",
         {"last_assistant_message": "## Plan\nStarting the audit."}, True),
        ("a heading with a trailing colon ends at its line break",
         {"last_assistant_message": "## Next:\nStarting the audit."}, True),
        ("a list item's unmarked paragraph continuation remains a plan item",
         {"last_assistant_message": "- item one\nStarting the audit."}, False),
        ("a numbered item's unmarked paragraph continuation remains a plan item",
         {"last_assistant_message": "1. item one\nStarting the audit."}, False),
        ("a quote's unmarked paragraph continuation remains quoted",
         {"last_assistant_message": "> Log says safe\nStarting the audit."}, False),
        ("a table's following unmarked line is prose",
         {"last_assistant_message": "| a | b |\n|---|---|\n| c | d |\nStarting the audit."},
         True),
        ("a wrapped quote stays quoted on every line",
         {"last_assistant_message": "> Log says safe\n> Starting the audit."}, False),
        ("consecutive plan items stay plan items",
         {"last_assistant_message": "- item one\n- Starting the audit."}, False),
        ("an issue reference is not a heading",
         {"last_assistant_message": "#12 fixed. Starting the audit."}, True),
        ("text inside a fence cannot retract a claim above it",
         {"last_assistant_message": "Starting the IR-38 audit.\n\n```\nlet me know```"},
         True),
        ("a bulleted handback is still a handback",
         {"last_assistant_message": "Starting the IR-38 audit.\n\n- let me know which "
                                    "you prefer"}, False),
        ("a quoted handback is still a handback",
         {"last_assistant_message": "Starting the IR-38 audit.\n\n> let me know which "
                                    "you prefer"}, False),
        ("a tilde fence is code for the handback read too",
         {"last_assistant_message": "Starting the IR-38 audit.\n\n~~~\nlet me know\n~~~"},
         True),
        ("a line inside a fence is a code sample, not a claim",
         {"last_assistant_message": "Two items closed.\n\n```\n- x\nStarting the audit\n"
                                    "```"}, False),
        ("a dash inside an option token is not a clause lead",
         {"last_assistant_message": "The flag is --Running the sweep in the config."},
         False),
        ("a semicolon ends a clause the way a full stop does",
         {"last_assistant_message": "The gate is green; starting the IR-38 audit."}, True),

        # The price of that strip, controlled. Each of these was allowed before and must
        # stay allowed: a matcher that buys the five cases above with any of them is a
        # matcher the reader learns to switch off.
        ("a hyphen inside a word is not a unit lead",
         {"last_assistant_message": "The sweep is long-running, so the receipt lands later."},
         False),
        ("a bulleted finding list is not an announcement",
         {"last_assistant_message": "Findings:\n\n- long-running sweep\n- residue green"},
         False),
        ("a status table row is not an announcement",
         {"last_assistant_message": "Agents:\n\n| worker | state |\n|---|---|\n"
                                    "| F1 | Running the sweep |"}, False),
        ("decoration inside a fence is code, not a claim",
         {"last_assistant_message": "Two items closed.\n\n```\n- Starting the audit\n```"},
         False),
        ("a closed fence releases the next unit back to prose",
         {"last_assistant_message": "```\nx = 1\n```\n\nStarting the IR-38 audit."}, True),
        # A sentence terminator not followed by whitespace is not a unit break, so the
        # matcher's `[.!?]` alternative is the only thing that can see this one. Without a
        # case for it, per-unit matching gives every other case a start-of-unit anchor and
        # that alternative can be deleted with the suite still green.
        ("a terminator with no space after it still ends a claim",
         {"last_assistant_message": "Two items closed.Starting the IR-38 audit."}, True),

        # The same opening words reporting work that RAN. Each of these was allowed before
        # the decoration strip because its marker hid it from the matcher, so closing the
        # markdown spellings put four report shapes in reach at the same time.
        ("an emphasised report of finished work is not an announcement",
         {"last_assistant_message": "**Running the sweep** completed in 4m."}, False),
        ("a bulleted report of finished work is not an announcement",
         {"last_assistant_message": "Findings:\n\n- Running the sweep finished at 12:04\n"
                                    "- residue green"}, False),
        ("a table row reporting a worker's state is not an announcement",
         {"last_assistant_message": "| state | worker |\n|---|---|\n"
                                    "| Running the sweep | F1 |"}, False),
        ("a clause reporting elapsed work is not an announcement",
         {"last_assistant_message": "The receipt landed; running the sweep took four "
                                    "minutes."}, False),
        # A report token is not portable evidence for every earlier clause. Each historical
        # result below belongs to another activity and therefore cannot excuse this one.
        ("a semicolon-separated historical failure does not excuse the announcement",
         {"last_assistant_message": "Starting the audit; the prior run failed."}, True),
        ("a colon-labelled historical failure does not excuse the announcement",
         {"last_assistant_message": "Starting the audit: the prior run failed."}, True),
        ("a timestamp colon stays inside the direct report",
         {"last_assistant_message": "Starting the audit at 12:04 failed."}, False),
        ("a ratio colon stays inside the direct report",
         {"last_assistant_message": "Running the sweep at 1:1 returned zero."}, False),
        ("a predicate directly after a colon still reports the activity",
         {"last_assistant_message": "Starting the audit: completed in 4m."}, False),
        ("URL punctuation stays inside the direct report",
         {"last_assistant_message":
          "Starting the audit at https://example.test failed."}, False),
        ("an image tag colon stays inside the direct report",
         {"last_assistant_message": "Starting the image:v1 audit failed."}, False),
        ("a URN colon stays inside the direct report",
         {"last_assistant_message": "Starting the urn:example audit failed."}, False),
        ("version dots stay inside the direct report",
         {"last_assistant_message": "Starting the v1.2.3 audit failed."}, False),
        ("an attached CLI option stays inside the direct report",
         {"last_assistant_message": "Starting the audit with --verbose failed."}, False),
        ("an ASCII-dash historical failure does not excuse the announcement",
         {"last_assistant_message": "Starting the audit -- the prior run failed."}, True),
        ("an em-dash historical failure does not excuse the announcement",
         {"last_assistant_message": "Starting the audit — the prior run failed."}, True),
        ("a causal historical failure does not excuse the announcement",
         {"last_assistant_message": "Starting the audit because the previous run failed."},
         True),
        ("a temporal historical result does not excuse the announcement",
         {"last_assistant_message": "Starting the audit after the checks passed."}, True),
        ("a direct completion predicate still reports the activity",
         {"last_assistant_message": "Running the sweep completed in 4m."}, False),
        ("a direct elapsed predicate still reports the activity",
         {"last_assistant_message": "Starting the audit took four minutes."}, False),
        ("a direct failure predicate still reports the activity",
         {"last_assistant_message": "Proceeding with step 3 failed at 12:04."}, False),
        ("a report adjective before the activity noun is not evidence",
         {"last_assistant_message": "Starting the failed audit."}, True),
        ("a report adjective after a dangling preposition is not evidence",
         {"last_assistant_message": "Starting the audit for failed checks."}, True),
        ("an aspect marker plus a report adjective is not evidence",
         {"last_assistant_message": "Starting the already completed audit."}, True),
        ("a future passive is not a completed-work report",
         {"last_assistant_message": "Running the sweep will be completed tomorrow."}, True),
        # An interrogative complement names what the announced activity will decide; the
        # report token inside it is not that activity's predicate. The conditional
        # siblings (if, unless, once) were already clause breaks.
        ("a whether complement does not report the announced activity",
         {"last_assistant_message": "Starting the audit of whether the tests passed."},
         True),
        ("a why complement does not report the announced activity",
         {"last_assistant_message":
          "Starting the investigation into why the tests failed."}, True),
        ("a how complement does not report the announced activity",
         {"last_assistant_message": "Starting the review of how the migration failed."},
         True),
        ("a where complement does not report the announced activity",
         {"last_assistant_message": "Starting the search for where the check failed."},
         True),
        ("a what complement does not report the announced activity",
         {"last_assistant_message": "Starting the review of what the sweep produced."},
         True),
        ("a what complement cannot excuse a let-me announcement",
         {"last_assistant_message": "Let me check what the sweep produced."}, True),
        ("a result tail cannot excuse a let-me announcement",
         {"last_assistant_message": "Let me verify the checks passed earlier."}, True),
        ("a bare future completion is not a completed-work report",
         {"last_assistant_message": "Running the sweep will be finished."}, True),
        ("a result verb after a dangling determiner is not evidence",
         {"last_assistant_message": "Starting the audit of the produced artifacts."},
         True),
        ("a result verb keeps its plain object",
         {"last_assistant_message": "Running the sweep produced output."}, False),
        ("an embedded report token inside a larger word is not a predicate",
         {"last_assistant_message": "Starting the re/completed after checks."}, True),
        ("terminal punctuation directly at a report token stays a clause break",
         {"last_assistant_message": "Starting the audit;failed to excuse it."}, True),
        ("a first line keeps the indentation it was written with",
         {"last_assistant_message": "    > deep\nStarting the audit."}, True),
        ("a genuine report cannot hide a later announcement in the same unit",
         {"last_assistant_message": "Running the sweep completed in 4m; starting the audit."},
         True),
        ("a report in the NEXT sentence does not excuse this one",
         {"last_assistant_message": "Starting the IR-38 audit. The last one took an hour."},
         True),
        # The escape reads the rest of the unit AFTER the trigger, not the whole unit: a
        # report of the previous run is not a report of this claim, and reading the whole
        # unit would let any completed-work sentence carry an announcement past the gate.
        ("a report BEFORE the trigger does not excuse it",
         {"last_assistant_message": "The last one took an hour; starting the IR-38 audit."},
         True),
        ("this repository's own dash spelling ends a clause too",
         {"last_assistant_message": "The gate is green -- starting the IR-38 audit."}, True),
        ("a hyphen inside a word is still not a dash",
         {"last_assistant_message": "The sweep is long-running -- the receipt lands later."},
         False),
        ("an unclosed fence keeps its remainder code",
         {"last_assistant_message": "Two items closed.\n\n```\n- Starting the audit"},
         False),
        # Why DECORATION stops short of the backtick. Inline code quotes a string rather
        # than claiming it, and this file's own prose ends on quoted matcher text.
        ("an inline code span quotes a claim rather than making one",
         {"last_assistant_message": "The matcher fires on this tail.\n\n"
                                    "`Starting the audit`"}, False),
        # The declared out-of-scope boundary, pinned as a case so widening it is a
        # deliberate edit rather than a drift. A colon labels what follows instead of
        # ending a clause, and the shape below is the cost of treating it as a terminator.
        ("a colon and a space is not an anchor",
         {"last_assistant_message": "Two items remain. Next: I\'ll now run the sweep."},
         False),
        ("a colon and a line break is, because the break is",
         {"last_assistant_message": "Two items remain. Next:\nI\'ll now run the sweep."},
         True),
        ("a labelled report of running work is not an announcement",
         {"last_assistant_message": "Background: Running the sweep in eight shards. "
                                    "The receipt lands when it finishes."}, False),

        # Decision arms that had no case of their own.
        ("empty text is not evidence of a defect", {"last_assistant_message": "   "}, False),
        ("an announcement handed back to the user does not block",
         {"last_assistant_message": "Starting the audit. Say the word and I will."}, False),
        ("the loop guard never re-blocks",
         {"last_assistant_message": "Starting the audit.", "stop_hook_active": True}, False),
    ]

    # The cases above compare block-vs-allow, so the RETURNED trigger is unasserted:
    # returning a bare True or False for it keeps every one of them green while the block
    # message quotes the wrong text back. The message is the whole output of a block.
    for label, message, trigger in (
        ("the blocked trigger is the announcement, quoted",
         "Right. Starting the IR-38 audit.", "Starting the"),
        ("an emphasised trigger loses its markup, not its words",
         "**Starting the IR-38 audit.**", "Starting the"),
        ("a clause trigger carries the lead that anchored it",
         "The gate is green; starting the IR-38 audit.", "; starting the"),
    ):
        got = judge({"last_assistant_message": message})
        ok = got == trigger
        failures += 0 if ok else 1
        checks += 1
        print(f"  {'PASS' if ok else 'FAIL'} {label} -> {got!r}")

    # Every drift arm reports, so asserting only THAT it drifted is satisfied by whichever
    # arm fires first: removing the type check still drifts, from the missing-key branch one
    # line below. These bind to the diagnosis instead.
    for label, payload, fragment in (
            ("a non-object payload names the type it got", "not an object",
             "parsed to str"),
            ("a payload missing the key names the key", {}, "no 'last_assistant_message'"),
            ("an unmodelled message type names the type", {"last_assistant_message": 17},
             "is a int"),
    ):
        try:
            message_text(payload)
            detail = ""
        except EnvelopeDrift as exc:
            detail = str(exc)
        ok = fragment in detail
        failures += 0 if ok else 1
        checks += 1
        print(f"  {'PASS' if ok else 'FAIL'} {label}")

    for name, payload, want in cases:
        if isinstance(payload, dict) and "__contract__" in payload:
            got = "contract" if payload["__contract__"] else "BROKEN"
            if got != want:
                failures += 1
            checks += 1
            print(f"  {'PASS' if got == want else 'FAIL'} {name} -> {got}")
            continue
        try:
            got = judge(payload) is not None
        except EnvelopeDrift:
            got = "drift"
        if got != want:
            failures += 1
        checks += 1
        label = got if isinstance(got, str) else ("block" if got else "allow")
        print(f"  {'PASS' if got == want else 'FAIL'} {name} -> {label}")

    # Count scanned/copied characters at the sentence-to-block seam. The two fixed sizes
    # exercise real boundary(), not a duplicate algorithm; a growing-prefix search or
    # slice exceeds the linear work allowance without depending on host timing.
    original_blocks = markdown_blocks
    for repetitions in (2048, 4096):
        work = {"block_chars": 0, "copied": 0, "searched": 0}

        class MeasuredBlock(str):
            def __getitem__(self, key):
                result = super().__getitem__(key)
                if isinstance(key, slice):
                    work["copied"] += len(result)
                return result

            def rfind(self, sub, start=0, end=None):
                bound = len(self) if end is None else end
                work["searched"] += max(0, bound - start)
                return super().rfind(sub, start, bound)

        def measured_blocks(text):
            for block, code, container in original_blocks(text):
                work["block_chars"] += len(block)
                yield MeasuredBlock(block), code, container

        message = "x. " * repetitions + "Starting the audit."
        globals()["markdown_blocks"] = measured_blocks
        try:
            got = boundary(message)
            ok = (got == [("x.", False, False), ("Starting the audit.", False, False)]
                  and work["block_chars"] == len(message)
                  and work["copied"] + work["searched"] <= 4 * len(message))
        except Exception:
            ok = False
        finally:
            globals()["markdown_blocks"] = original_blocks
        failures += 0 if ok else 1
        checks += 1
        print(f"  {'PASS' if ok else 'FAIL'} boundary progress n={repetitions} -> {work}")

    # Production-path controls: these enter through JSON stdin and assert the hook's actual
    # exit/receipt contract, not only judge(). The direct cases above localise failures; this
    # matrix proves main() still carries each decision to the Stop host correctly.
    environment = dict(os.environ)
    environment.pop("ANNOUNCED_WORK_GUARD", None)
    # This is the demonstrated 360019-byte message, at the registered five-second budget.
    # A timeout is one failed check, not an aborted suite with a different cardinality.
    try:
        large = subprocess.run(
            [sys.executable, os.path.abspath(__file__)],
            input=json.dumps({"hook_event_name": "Stop",
                              "last_assistant_message": "x. " * 120000
                              + "Starting the audit."}),
            capture_output=True, text=True, timeout=5, env=environment)
        ok = (large.returncode == 2 and not large.stdout
              and "'Starting the'" in large.stderr)
    except subprocess.TimeoutExpired:
        ok = False
    failures += 0 if ok else 1
    checks += 1
    print(f"  {'PASS' if ok else 'FAIL'} main answers the 360019-byte scale case in budget")
    # The single-unit shapes: report tokens flooding one sentence, spaced and embedded.
    # These reach reports_this_activity, which the many-sentence case above never does;
    # a growing-prefix rescan there times the guard out into an allow at thirty kilobytes.
    for label, scale_message in (
        ("main answers a 400016-byte report-token flood in budget",
         "Starting the " + "failed of " * 40000 + "end"),
        ("main answers a 289028-byte embedded-report token in budget",
         "Starting the audit " + "-failed" * 41287 + " and more"),
    ):
        try:
            scaled = subprocess.run(
                [sys.executable, os.path.abspath(__file__)],
                input=json.dumps({"hook_event_name": "Stop",
                                  "last_assistant_message": scale_message}),
                capture_output=True, text=True, timeout=5, env=environment)
            ok = (scaled.returncode == 2 and not scaled.stdout
                  and "'Starting the'" in scaled.stderr)
        except subprocess.TimeoutExpired:
            ok = False
        failures += 0 if ok else 1
        checks += 1
        print(f"  {'PASS' if ok else 'FAIL'} {label}")
    for label, message, want, trigger in (
        ("main blocks a semicolon-separated historical report",
         "Starting the audit; the prior run failed.", 2, "Starting the"),
        ("main blocks a colon-labelled historical report",
         "Starting the audit: the prior run failed.", 2, "Starting the"),
        ("main keeps a timestamp colon inside the direct report",
         "Starting the audit at 12:04 failed.", 0, None),
        ("main keeps a predicate directly after a colon with the activity",
         "Starting the audit: completed in 4m.", 0, None),
        ("main keeps URL punctuation inside the direct report",
         "Starting the audit at https://example.test failed.", 0, None),
        ("main keeps version dots inside the direct report",
         "Starting the v1.2.3 audit failed.", 0, None),
        ("main keeps an attached CLI option inside the direct report",
         "Starting the audit with --verbose failed.", 0, None),
        ("main blocks an ASCII-dash historical report",
         "Starting the audit -- the prior run failed.", 2, "Starting the"),
        ("main blocks an em-dash historical report",
         "Starting the audit — the prior run failed.", 2, "Starting the"),
        ("main blocks a causal historical report",
         "Starting the audit because the previous run failed.", 2, "Starting the"),
        ("main blocks a temporal historical report",
         "Starting the audit after the checks passed.", 2, "Starting the"),
        ("main allows the activity's direct completed-work predicate",
         "Running the sweep completed in 4m.", 0, None),
        ("main blocks a word-counted failure adjective",
         "Running the three failed tests.", 2, "Running the"),
        ("main blocks a digit-counted failure adjective",
         "Running the 3 failed tests.", 2, "Running the"),
        ("main blocks a remaining-object failure adjective",
         "Running the remaining failed tests.", 2, "Running the"),
        ("main blocks an ordinal completion adjective",
         "Starting the second completed audit.", 2, "Starting the"),
        ("main blocks a digit-counted completion adjective",
         "Starting the 2 completed audits.", 2, "Starting the"),
        ("main blocks an ambiguous object after a completion token",
         "Running the script completed tasks.", 2, "Running the"),
        ("main allows a counted object's direct failure predicate",
         "Running the three tests failed.", 0, None),
        ("main allows a counted object's direct completion predicate",
         "Starting the second audit completed in 4m.", 0, None),
        ("main associates the predicate after a failure adjective",
         "Running the three failed tests completed in 4m.", 0, None),
        ("main associates the predicate after a completion adjective",
         "Starting the second completed audit failed.", 0, None),
        ("main retains object-taking result predicates",
         "Running the sweep produced three files.", 0, None),
        ("main retains a completion predicate with a determiner-led result object",
         "Running the script completed the migration.", 0, None),
        ("main retains a finishing predicate with a determiner-led result object",
         "Running the script finished the conversion.", 0, None),
        ("main retains a passing predicate with a quantified result object",
         "Running the test suite passed all checks.", 0, None),
        ("main retains a failing predicate with a word-counted result object",
         "Running the validator failed three invalid requests.", 0, None),
        ("main retains a digit-counted result object",
         "Running the test suite passed 12 checks.", 0, None),
        ("main retains a compound word-counted result object",
         "Running the validator failed twenty-four invalid requests.", 0, None),
        ("main retains a both-quantified result object",
         "Running the script completed both migrations.", 0, None),
        ("main retains an each-quantified result object",
         "Running the script finished each conversion.", 0, None),
        ("main still rejects a counted completion adjective before its noun",
         "Running the three completed migrations.", 2, "Running the"),
        ("main still rejects a counted failure adjective before its noun",
         "Running the three failed checks.", 2, "Running the"),
        ("main retains a result adverb",
         "Running the sweep completed successfully.", 0, None),
        ("main blocks a what complement on the participle arm",
         "Starting the review of what the sweep produced.", 2, "Starting the"),
        ("main blocks a whether complement on the participle arm",
         "Starting the audit of whether the tests passed.", 2, "Starting the"),
        ("main blocks a why complement on the participle arm",
         "Starting the investigation into why the tests failed.", 2, "Starting the"),
        ("main keeps a first line's own indentation",
         "    > deep\nStarting the audit.", 2, "Starting the"),
        ("main blocks a let-me whether complement",
         "Let me check whether the tests passed.", 2, "Let me check"),
        ("main blocks an imminent whether complement",
         "I'll now check whether the tests passed.", 2, "I'll now check"),
        ("main blocks a let-me why complement",
         "Let me check why the tests failed.", 2, "Let me check"),
        ("main blocks an imminent where complement",
         "I'll now check where the tests failed.", 2, "I'll now check"),
        ("main checks a later announcement after a genuine report",
         "Running the sweep completed in 4m; starting the audit.", 2, "; starting the"),
        ("main preserves a quote container across sentence splitting",
         "> Log says safe. Starting the audit.", 0, None),
        ("main preserves a hyphen list across sentence splitting",
         "- Status note. Starting the audit.", 0, None),
        ("main distinguishes an asterisk list from emphasis",
         "* Status note. Starting the audit.", 0, None),
        ("main preserves a table row across sentence splitting",
         "| Status note. Starting the audit. |", 0, None),
        ("main preserves a heading across sentence splitting",
         "## Status note. Starting the audit.", 0, None),
        ("main still blocks the plain-prose control",
         "Log says safe. Starting the audit.", 2, "Starting the"),
        ("main reads the line under a heading as prose",
         "## Plan\nStarting the audit.", 2, "Starting the"),
        ("main preserves a list item's lazy paragraph continuation",
         "- item one\nStarting the audit.", 0, None),
        ("main reads an issue reference as prose",
         "#12 fixed. Starting the audit.", 2, "Starting the"),
        ("main keeps a wrapped quote quoted",
         "> Log says safe\n> Starting the audit.", 0, None),
        ("main keeps a lazy quote continuation quoted",
         "> Log says safe\nStarting the audit.", 0, None),
        ("main preserves an ordered item's lazy continuation",
         "1. item one\nStarting the audit.", 0, None),
        ("main preserves a plus item's lazy continuation",
         "+ item one\nStarting the audit.", 0, None),
        ("main preserves an asterisk item's lazy continuation",
         "* item one\nStarting the audit.", 0, None),
        ("main preserves an indented list continuation",
         "- item one\n  Starting the audit.", 0, None),
        ("main preserves an indented ordered continuation",
         "1. item one\n   Starting the audit.", 0, None),
        ("main retains an indented list paragraph after a blank line",
         "- item one\n\n  Starting the audit.", 0, None),
        ("main ends a lazy quote at a blank line",
         "> Log says safe\n\nStarting the audit.", 2, "Starting the"),
        ("main ends a lazy list at a blank line",
         "- item one\n\nStarting the audit.", 2, "Starting the"),
        ("main does not lazily continue a quoted heading",
         "> ## Plan\nStarting the audit.", 2, "Starting the"),
        ("main does not lazily continue a list heading",
         "- ## Plan\nStarting the audit.", 2, "Starting the"),
        ("main reads prose immediately after a backtick closer",
         "```\nx = 1\n```\nStarting the audit.", 2, "Starting the"),
        ("main reads prose immediately after a tilde closer",
         "~~~\nx = 1\n~~~\nStarting the audit.", 2, "Starting the"),
        ("main reads prose after a tilde closer and blank line",
         "~~~\nx = 1\n~~~\n\nStarting the audit.", 2, "Starting the"),
        ("main accepts a longer matching closer",
         "```\nx = 1\n`````\nStarting the audit.", 2, "Starting the"),
        ("main rejects a shorter closer",
         "````\nx = 1\n```\n\nStarting the audit.", 0, None),
        ("main rejects a different delimiter as a closer",
         "```\nx = 1\n~~~\n\nStarting the audit.", 0, None),
        ("main rejects a shorter tilde closer",
         "~~~~\nx = 1\n~~~\n\nStarting the audit.", 0, None),
        ("main rejects a quoted delimiter inside top-level code",
         "```\n> ```\nStarting the audit.", 0, None),
        ("main keeps an extra quote marker literal inside quoted code",
         "> ```\n> > ```\n> Starting the audit.", 0, None),
        ("main rejects a closer with non-whitespace suffix",
         "```\nx = 1\n``` not closed\nStarting the audit.", 0, None),
        ("main retains an unclosed tilde block",
         "~~~\nx = 1\n\nStarting the audit.", 0, None),
        ("main does not open a backtick fence with backticks in its info string",
         "```lang`\nStarting the audit.", 2, "Starting the"),
        ("main excludes backtick code from the handback read",
         "Starting the audit.\n\n```\nlet me know\n```", 2, "Starting the"),
        ("main excludes tilde code from the handback read",
         "Starting the audit.\n\n~~~\nlet me know\n~~~", 2, "Starting the"),
        ("main excludes a question inside an unclosed backtick block",
         "Starting the audit.\n\n```\nexample?", 2, "Starting the"),
        ("main excludes a question inside an unclosed tilde block",
         "Starting the audit.\n\n~~~\nexample?", 2, "Starting the"),
        ("main excludes a question inside a closed backtick block",
         "Starting the audit.\n\n```\nexample?\n```", 2, "Starting the"),
        ("main excludes a question inside a closed tilde block",
         "Starting the audit.\n\n~~~\nexample?\n~~~", 2, "Starting the"),
        ("main retains a direct question handback",
         "Starting the audit; is that the next step?", 0, None),
        ("main retains a quoted question handback",
         "Starting the audit.\n\n> Is that the next step?", 0, None),
        ("main retains a listed question handback",
         "Starting the audit.\n\n- Is that the next step?", 0, None),
        ("main retains a question handback followed by backtick code",
         "Starting the audit; is that the next step?\n\n```\nexample\n```", 0, None),
        ("main retains a question handback followed by tilde code",
         "Starting the audit; is that the next step?\n\n~~~\nexample\n~~~", 0, None),
        ("main counts a punctuated backtick block as one tail unit",
         "Starting the audit.\n\n```\nfirst. second. third.\n```", 2, "Starting the"),
        ("main counts a punctuated tilde block as one tail unit",
         "Starting the audit.\n\n~~~\nfirst. second. third.\n~~~", 2, "Starting the"),
        ("main excludes a quoted fence from the handback read",
         "Starting the audit.\n\n> ```\n> let me know\n> ```", 2, "Starting the"),
        ("main releases an unclosed quoted fence when its container ends",
         "> ```\n> code\nStarting the audit.", 2, "Starting the"),
        ("main retains a direct result before a closed code block",
         "Running the sweep completed in 4m.\n\n```\nx = 1\n```", 0, None),
        ("main excludes an announcement before two later structural units",
         "Starting the audit.\n\n```\nx = 1\n```\n\n## Results", 0, None),
    ):
        done = subprocess.run(
            [sys.executable, os.path.abspath(__file__)],
            input=json.dumps({"hook_event_name": "Stop",
                              "last_assistant_message": message}),
            capture_output=True, text=True, timeout=5, env=environment)
        ok = (done.returncode == want
              and ((want == 0 and not done.stdout and not done.stderr)
                   or (want == 2 and not done.stdout and trigger in done.stderr)))
        failures += 0 if ok else 1
        checks += 1
        print(f"  {'PASS' if ok else 'FAIL'} {label} -> rc={done.returncode}")

    # Line-ending framing preserves both report meaning and fence boundaries. Paragraphs
    # and containers remain separate units and cannot supply a missing predicate.
    for ending_name, ending in (("LF", "\n"), ("CRLF", "\r\n")):
        for label, message, want in (
            ("wrapped completion object", "Running the script completed\nthe migration.", 0),
            ("wrapped finishing object", "Running the script finished\nevery conversion.", 0),
            ("wrapped passing object", "Running the test suite passed\nall checks.", 0),
            ("wrapped failing object", "Running the validator failed\nthree invalid requests.", 0),
            ("wrapped result modifier", "Running the audit completed\nin four minutes.", 0),
            ("wrapped failure adjective", "Running the three failed\nchecks.", 2),
            ("wrapped completion adjective", "Starting the second completed\naudit.", 2),
            ("separate paragraph result", "Running the audit\n\nThe prior run failed.", 2),
            ("separate heading result", "Running the audit\n## The prior run failed.", 2),
            ("separate quote result", "Running the audit\n> The prior run failed.", 2),
            ("closed backtick fence", "```\nexample\n```\nStarting the audit.", 2),
            ("closed tilde fence", "~~~\nexample\n~~~\nStarting the audit.", 2),
            ("longer backtick closer", "```\nexample\n`````\nStarting the audit.", 2),
            ("longer tilde closer", "~~~\nexample\n~~~~~\nStarting the audit.", 2),
            ("indented fence closer", "```\nexample\n   ```\nStarting the audit.", 2),
            ("fence closer with horizontal space",
             "```\nexample\n``` \t\nStarting the audit.", 2),
            ("shorter backtick is not a closer",
             "````\nexample\n```\nStarting the audit.", 0),
            ("shorter tilde is not a closer", "~~~~\nexample\n~~~\nStarting the audit.", 0),
            ("different fence kind is not a closer",
             "```\nexample\n~~~\nStarting the audit.", 0),
            ("text after a delimiter is not a closer",
             "```\nexample\n``` text\nStarting the audit.", 0),
            ("unclosed fence", "```\nexample\nStarting the audit.", 0),
            ("code question cannot hand back",
             "Starting the audit.\n\n```\nexample?\n```", 2),
            ("question after a closer can hand back",
             "Starting the audit.\n\n```\nexample\n```\nShould I proceed?", 0),
            ("heading after a closer supplies another structural unit",
             "Starting the audit.\n\n```\nexample\n```\n## Results", 0),
            ("closed quoted fence", "> ```\n> example\n> ```\nStarting the audit.", 2),
            ("closed list fence", "- ```\n  example\n  ```\n\nStarting the audit.", 2),
        ):
            done = subprocess.run(
                [sys.executable, os.path.abspath(__file__)],
                input=json.dumps({"hook_event_name": "Stop",
                                  "last_assistant_message": message.replace("\n", ending)}),
                capture_output=True, text=True, timeout=5, env=environment)
            ok = (done.returncode == want and not done.stdout
                  and ((want == 0 and not done.stderr)
                       or (want == 2 and "Your final sentence announces work" in done.stderr)))
            failures += 0 if ok else 1
            checks += 1
            print(f"  {'PASS' if ok else 'FAIL'} main {ending_name} {label} -> rc={done.returncode}")

    # Envelope and switch controls through main(): the off switch on each of its three
    # arms, an event outside this guard's scope, a payload that is not an object, and
    # stdin that is not JSON. The matrix above holds the envelope fixed and cannot reach
    # these; each is the hook's own exit and receipt as the Stop host sees them.
    off_environment = dict(environment, ANNOUNCED_WORK_GUARD="off")
    announcing = json.dumps({"hook_event_name": "Stop",
                             "last_assistant_message": "Starting the audit."})
    # Both accepted block-list envelopes use the same value validator. Each case enters
    # main() so a TypeError, a coerced value, or a missing drift receipt cannot pass.
    for shape in ("bare", "content"):
        for value, expected, receipt in (
                (None, 2, "text block 1 has NoneType text, expected str"),
                (7, 2, "text block 1 has int text, expected str"),
                (True, 2, "text block 1 has bool text, expected str"),
                (1.25, 2, "text block 1 has float text, expected str"),
                ([], 2, "text block 1 has list text, expected str"),
                ({"value": "Starting the audit."}, 2,
                 "text block 1 has dict text, expected str"),
                ("Starting the audit.", 2, "Your final sentence announces work"),
                ("", 0, None)):
            blocks = [{"type": "thinking", "text": None},
                      {"type": "text", "text": value}]
            message = blocks if shape == "bare" else {"content": blocks}
            done = subprocess.run(
                [sys.executable, os.path.abspath(__file__)],
                input=json.dumps({"hook_event_name": "Stop",
                                  "last_assistant_message": message}),
                capture_output=True, text=True, timeout=5, env=environment)
            ok = (done.returncode == expected and not done.stdout
                  and ((receipt is None and not done.stderr)
                       or (receipt is not None and receipt in done.stderr
                           and "Traceback" not in done.stderr)))
            failures += 0 if ok else 1
            checks += 1
            print(f"  {'PASS' if ok else 'FAIL'} main reads {shape} text-block "
                  f"{type(value).__name__} -> rc={done.returncode}")

    for label, raw, env, want, needle in (
        ("main blocks the announcement the switch controls start from",
         announcing, environment, 2, "Starting the"),
        ("main honours the off switch for an announcement",
         announcing, off_environment, 0, None),
        ("main reports stdin that is not JSON as drift",
         "not json", environment, 2, "stdin is not JSON"),
        ("main honours the off switch for stdin that is not JSON",
         "not json", off_environment, 0, None),
        ("main reports a payload that is not an object as drift",
         json.dumps(["Starting the audit."]), environment, 2, "expected a JSON object"),
        ("main honours the off switch for envelope drift",
         json.dumps(["Starting the audit."]), off_environment, 0, None),
        ("main ignores an event outside its scope",
         json.dumps({"hook_event_name": "PreToolUse",
                     "last_assistant_message": "Starting the audit."}), environment, 0, None),
        ("main reads a SubagentStop event",
         json.dumps({"hook_event_name": "SubagentStop",
                     "last_assistant_message": "Starting the audit."}), environment, 2,
         "Starting the"),
    ):
        done = subprocess.run(
            [sys.executable, os.path.abspath(__file__)], input=raw,
            capture_output=True, text=True, timeout=5, env=env)
        ok = (done.returncode == want and not done.stdout
              and ((needle is None and not done.stderr)
                   or (needle is not None and needle in done.stderr)))
        failures += 0 if ok else 1
        checks += 1
        print(f"  {'PASS' if ok else 'FAIL'} {label} -> rc={done.returncode}")
    print(f"\n  selftest: {failures} failure(s)")
    print(f"SELFTEST-SUMMARY suite=announced_work_guard checks={checks} "
          f"failures={failures}")
    return failures == 0


def sweep(globs):
    """Re-run the false-positive measurement over real transcripts.

    The headline number in this file's history — 6 blocks in 2676 turns that
    end on text, 0.22% — is worthless as a literal: nobody can check it and it
    drifts the moment the matcher changes. This is the query that regenerates
    it, so a reviewer can disagree with the number instead of taking it.

    A turn is scored only when it ENDS on text. A turn whose last text is
    followed by a tool call is the healthy case by construction and is not a
    candidate, which is why the denominator here is smaller than the turn count.
    """
    import glob as _glob
    files = sorted({f for g in globs for f in _glob.glob(os.path.expanduser(g))})
    turns_n = ends = blocks = 0
    hits = []
    for path in files:
        turns, cur = [], []
        try:
            lines = open(path, encoding="utf-8", errors="replace").readlines()
        except OSError:
            continue
        for line in lines:
            try:
                d = json.loads(line)
            except ValueError:
                continue
            if d.get("isSidechain"):
                continue                        # subagent, not this turn
            c = (d.get("message") or {}).get("content")
            if d.get("type") == "user":
                # a user record carrying tool_result is the harness replying,
                # not a human turn boundary
                if isinstance(c, list) and any(
                        isinstance(b, dict) and b.get("type") == "tool_result" for b in c):
                    continue
                if cur:
                    turns.append(cur)
                    cur = []
                continue
            if d.get("type") == "assistant" and isinstance(c, list):
                for b in c:
                    if isinstance(b, dict) and b.get("type") in ("text", "tool_use"):
                        cur.append((b["type"], b.get("text", "") or b.get("name", "")))
        if cur:
            turns.append(cur)
        turns_n += len(turns)
        for t in turns:
            li = max((i for i, (k, _) in enumerate(t) if k == "text"), default=None)
            if li is None or any(k == "tool_use" for k, _ in t[li + 1:]):
                continue
            ends += 1
            try:
                trig = judge({"last_assistant_message": t[li][1]})
            except EnvelopeDrift:
                continue
            if trig:
                blocks += 1
                hits.append((os.path.basename(os.path.dirname(path))[-30:], trig,
                             " ".join(t[li][1][-120:].split())))
    print(f"# COVERAGE transcripts={len(files)} turns={turns_n} ending_on_text={ends}")
    print("#   NOT COVERED: a turn ending in a tool call cannot exhibit this defect and is "
          "excluded from the denominator, so this is a rate over CANDIDATES, not over turns.")
    print("#   NOT COVERED: whether each block is a TRUE positive. That is a human read; "
          "the tails are printed so it can be disagreed with.")
    print(f"\n# {blocks} block(s) / {ends} candidates = "
          f"{100 * blocks / max(ends, 1):.2f}%\n")
    for proj, trig, tail in hits:
        print(f"  [{proj}] {trig!r}\n     …{tail}")
    return 0


def main(argv):
    if "--selftest" in argv:
        return 0 if selftest() else 1
    if "--sweep" in argv:
        rest = argv[argv.index("--sweep") + 1:]
        return sweep(rest or ["~/.claude/projects/*/*.jsonl"])
    off = os.environ.get("ANNOUNCED_WORK_GUARD") == "off"
    raw = sys.stdin.read()
    try:
        payload = json.loads(raw)
    except Exception as exc:
        if off:
            return 0
        print(DRIFT_MSG.format(v=VERSION, why=f"stdin is not JSON ({exc})"), file=sys.stderr)
        return 2
    if isinstance(payload, dict) and \
            payload.get("hook_event_name") not in (None, "Stop", "SubagentStop"):
        return 0                        # out of scope, which is not drift
    try:
        trigger = judge(payload)
    except EnvelopeDrift as exc:
        if off:
            return 0
        print(DRIFT_MSG.format(v=VERSION, why=str(exc)), file=sys.stderr)
        return 2
    if not trigger or off:
        return 0
    print(BLOCK_MSG.format(v=VERSION, trigger=trigger), file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
